/* Integration layer: retain v4's rich business story; keep work in a persistent panel. */
const BASE={render,renderModal,modalFrame,showModal,closeModal,handle,persist,canvasHTML,sidebarHTML,headerHTML,composerHTML,messageHTML,contentHTML,assetVisual,fridge,posterSvg,makeContent,modifySelected,inspectContent,exportHTML,versionFiles,runWork,adopt,reviewDecision};
S.openCanvases??=[];S.panelStack??=[];S.panelDrafts??={};S.composerDrafts??={};S.workbenchWidth??=62;
const makeV4State=makeState;
makeState=()=>({...makeV4State(),openCanvases:[],panelStack:[],panelDrafts:{},composerDrafts:{},workbenchWidth:62,dockState:null});
Object.assign(DRAFTS,S.composerDrafts);
let panelRestore=S.dockState,renderGeneration=0,textObserver=null,textMutations=null,returnFocus=null;
const BLOCKING=new Set(['submit','reset','auto-confirm','restore-confirm']);
const UTILITY_PAGES=new Set(['settings','capabilities','capability']);
function isBlockingModal(kind){return BLOCKING.has(kind)}
function panelKey(m=MODAL){return m?m.kind+'|'+m.arg:''}
function capturePanel(){if(!MODAL||isBlockingModal(MODAL.kind))return;const values={};document.querySelectorAll('#modal-root input[id],#modal-root textarea[id],#modal-root select[id]').forEach(el=>{if(el.type!=='file')values[el.id]={value:el.value,checked:el.checked}});if(Object.keys(values).length)S.panelDrafts[panelKey()]={values,at:now()};}
persist=function(){capturePanel();S.composerDrafts={...DRAFTS};S.dockState=MODAL&&!isBlockingModal(MODAL.kind)?clone(MODAL):null;BASE.persist();};
function workTabs(){return `<nav class="work-tabs" aria-label="打开的工作面">${S.openCanvases.map(c=>{const a=artifact(c.id);if(!a)return'';const selected=!MODAL&&S.canvas?.id===c.id&&S.canvas.num===c.num;return `<div class="work-tab ${selected?'active':''}">${button(E(KIND[a.kind].name)+' · v'+c.num,'canvas-switch',c.id+'|'+c.num,'sm')}${ibutton('关闭 '+KIND[a.kind].name+' v'+c.num,'canvas-tab-close',c.id+'|'+c.num)}</div>`}).join('')}${MODAL&&!isBlockingModal(MODAL.kind)?`<div class="work-tab active"><span class="btn sm">${E(({source:'来源资料','run-detail':'执行过程','tool-detail':'工具详情',compare:'版本对比',review:'成果审核','edit-point':'编辑价值主题','edit-material':'编辑物料','edit-document':'编辑正文',scope:'交付范围',context:'项目上下文'})[MODAL.kind]||'工作详情')}</span></div>`:''}</nav>`}
function rememberCanvas(){S.openCanvases=[...new Map((S.openCanvases||[]).map(c=>[c.id,c])).values()];if(!S.canvas)return;const c=S.canvas,old=S.openCanvases.find(x=>x.id===c.id);if(old)old.num=c.num;else S.openCanvases.push({id:c.id,num:c.num});}
function dockRoot(){let root=document.querySelector('#modal-root');if(!root){root=document.createElement('div');root.id='modal-root';document.body.appendChild(root)}return root}
function mountDock(){const root=dockRoot(),main=document.querySelector('.main');if(!main)return;main.id='main-work';main.style.setProperty('--workbench-width',S.workbenchWidth+'%');const page=UTILITY_PAGES.has(MODAL?.kind),docked=MODAL&&!isBlockingModal(MODAL.kind)&&!page;main.classList.toggle('has-details',!!docked);main.classList.toggle('has-utility-page',page);if(docked||page){root.className=page?'utility-host':'dock-host';main.appendChild(root);if(docked)main.querySelector('.canvas')?.remove();}else{root.className='';document.body.appendChild(root)}if(!page&&(S.canvas||docked)){if(!main.querySelector('.work-resizer')){const resize=document.createElement('button');resize.className='work-resizer';resize.setAttribute('aria-label','调整工作面宽度');resize.setAttribute('role','separator');resize.setAttribute('aria-orientation','vertical');resize.tabIndex=0;main.appendChild(resize)}}}
modalFrame=function(title,body,foot='',wide=false){if(isBlockingModal(MODAL?.kind))return BASE.modalFrame(title,body,foot,wide);if(UTILITY_PAGES.has(MODAL?.kind))return `<section class="utility-page" aria-label="${E(title)}"><header class="modal-head">${button('返回工作','utility-close','','ghost sm','chevron')}<h1 id="modal-title">${title}</h1></header><div class="modal-body">${body}</div>${foot?`<footer class="modal-foot">${foot}</footer>`:''}</section>`;const back=S.panelStack.length?button(icon('chevron')+'返回','panel-back','','ghost sm breadcrumb-back'):S.canvas?button('返回成果','modal-close','','ghost sm'):'';return workTabs()+`<section class="dock-panel" role="region" aria-label="${E(title)}"><header class="modal-head">${back}<h2 id="modal-title">${title}</h2>${S.runId&&['run-detail','tool-detail'].includes(MODAL?.kind)?'<span class="live-label">实时更新</span>':''}${ibutton('收起详情','panel-close')}</header><div class="modal-body">${body}</div>${foot?`<footer class="modal-foot">${foot}</footer>`:''}</section>`};
function restorePanelValues(){const saved=S.panelDrafts[panelKey()];if(!saved)return;for(const [id,v] of Object.entries(saved.values)){const el=document.getElementById(id);if(el){el.value=v.value;if(el.type==='checkbox')el.checked=v.checked}}}
showModal=function(kind,arg=''){capturePanel();returnFocus=document.activeElement;if(MODAL&&!isBlockingModal(MODAL.kind)&&!isBlockingModal(kind)&&panelKey()!==kind+'|'+arg)S.panelStack.push(clone(MODAL));MODAL={kind,arg};if(kind==='scope'){const p=project(arg);if(!p)return;scopeDraft={channels:[...p.channels],tier:p.tier,selected:p.scopeConfirmed?(p.scope||[]).map(x=>x.kind):rulesFor(p.channels,p.tier).filter(r=>r.category!=='推荐').map(r=>r.kind)}}render();renderModal();persist();if(isBlockingModal(kind))requestAnimationFrame(()=>document.querySelector('#modal-root button')?.focus());};
closeModal=function(){capturePanel();MODAL=null;S.panelStack=[];S.dockState=null;const root=dockRoot();document.body.appendChild(root);root.innerHTML='';root.className='';render();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});persist();};
renderModal=function(){if(!MODAL)return;const root=dockRoot(),scroll=root.querySelector('.modal-body')?.scrollTop||0;capturePanel();
  if(MODAL.kind==='edit-document'){const[id,n]=MODAL.arg.split('|'),a=artifact(id),v=revision(a,+n);if(!a||!v)return;let fields=[];if(v.data.sections)fields=v.data.sections.map((sec,i)=>({path:'sections.'+i+'.body',label:sec.title,value:sec.body}));else if(a.kind==='mh')fields=[{path:'claim',label:'产品主张',value:v.data.claim},{path:'needs',label:'消费者需求',value:v.data.needs},{path:'emotion',label:'情感价值',value:v.data.emotion},{path:'summary',label:'表达摘要',value:v.data.summary},...v.data.points.flatMap((p,i)=>[{path:'points.'+i+'.claim',label:p.title+' · 卖点主张',value:p.claim},{path:'points.'+i+'.long',label:p.title+' · 完整文案',value:p.long}])];root.innerHTML=modalFrame('编辑 '+a.title,`<div class="notice editor-notice">编辑自动保存为本地工作底稿。保存候选后再决定采用，已有提交和批准版不变。</div>${fields.map((f,i)=>`${a.kind==='mh'&&(i===0||f.path.endsWith('.claim'))?`<h3 class="editor-group-title">${i===0?'整体表达':E(v.data.points[Number(f.path.split('.')[1])].title)}</h3>`:''}<div class="field edit-section"><label for="doc-field-${i}">${E(f.label)}</label><textarea id="doc-field-${i}" data-doc-path="${f.path}">${E(f.value)}</textarea></div>`).join('')}`,button('返回成果','modal-close')+button('保存为新候选','save-document',MODAL.arg,'primary'));
  }else if(MODAL.kind==='restore-confirm'){root.innerHTML=modalFrame('恢复工作备份',`<p>将恢复 ${window.pendingBackup?.projects?.length||0} 个项目和 ${window.pendingBackup?.artifacts?.length||0} 份成果。当前内容可以先导出备份。</p>`,button('取消','modal-close')+button('先导出当前备份','export-backup')+button('恢复此备份','restore-confirm','', 'primary'));
  }else BASE.renderModal();
  mountDock();restorePanelValues();const body=root.querySelector('.modal-body');if(body)body.scrollTop=scroll;
  if(MODAL.kind==='settings'){root.querySelector('.notice').textContent='打开来源和工具详情不会暂停工作；需要暂停时使用执行控制。编辑底稿与输入框会在刷新后恢复。';root.querySelector('.modal-foot')?.insertAdjacentHTML('afterbegin',button('恢复备份','restore-backup')+button('导出备份','export-backup'));}
  if(MODAL.kind==='about'){root.querySelectorAll('.section p').forEach(p=>{p.textContent=p.textContent.replace('Midea 为文字名称，不冒充官方字标。产品数值沿用附件记录，图片为继承的概念示意，非实际商业物料。','沿用美的官方字标与已归档的 SpaceMaster 产品照片；厨房背景保留 v4 概念示意并标注，商业使用授权待确认。')});}
  if(MODAL.kind==='asset-detail'){const notice=root.querySelector('.notice.warn');if(notice)notice.textContent='三张产品照片来自原型项目的目标型号官网归档；厨房背景为 v4 概念示意。演示可选不代表商业使用授权。';}
  if(MODAL.kind==='edit-material'){const select=root.querySelector('#mat-image');if(select)select.innerHTML=[['front','正面产品图'],['angle','左侧产品图'],['right','右侧产品图'],...S.uploads.filter(x=>x.type==='image'&&x.eligible).map(x=>[x.id,x.name])].map(([k,l])=>`<option value="${E(k)}">${E(l)}</option>`).join('');restorePanelValues();if(select&&!S.panelDrafts[panelKey()])select.value=revision(artifact(MODAL.arg.split('|')[0]),+MODAL.arg.split('|')[1]).data.image||'front';}
  if(['run-detail','tool-detail'].includes(MODAL.kind)){const last=root.querySelector('.modal-foot .btn');if(last)last.textContent='返回工作';}
  scheduleText();
};
canvasHTML=function(){return BASE.canvasHTML().replace('<div class="canvas-head">',workTabs()+'<div class="canvas-head">')};
render=function(bottom=false){const root=dockRoot(),old=document.querySelector('#composer');capturePanel();if(old?.dataset.threadId){DRAFTS[old.dataset.threadId]=old.value;if(old.dataset.threadId!==S.threadId){old.value=DRAFTS[S.threadId]||'';old.dataset.threadId=S.threadId;}}document.body.appendChild(root);rememberCanvas();BASE.render(bottom);const comp=document.querySelector('#composer');if(comp)comp.dataset.threadId=S.threadId;mountDock();if(MODAL)renderModal();requestAnimationFrame(()=>{const tab=document.querySelector('.work-tabs .active'),strip=tab?.parentElement;if(tab?.getClientRects().length&&strip){const x=tab.offsetLeft-strip.offsetLeft;if(x<strip.scrollLeft)strip.scrollLeft=x;else if(x+tab.offsetWidth>strip.scrollLeft+strip.clientWidth)strip.scrollLeft=x+tab.offsetWidth-strip.clientWidth;}});scheduleText();};
sidebarHTML=function(){const p=project();let html=BASE.sidebarHTML();html=html.replace(/<div><div class="wordmark">Lilith<\/div><div class="brand-sub">.*?<\/div><\/div>/,`<div class="brand-lockup"><div class="wordmark">Lilith</div><span class="line"></span><img src="${MERGED_ASSETS.logo}" alt="Midea"></div>`);
 const start=html.indexOf('<div class="nav-label">最近对话</div>'),end=html.indexOf('</div><div class="sidebar-bottom">',start);
 if(start>=0&&end>=0)html=html.slice(0,start)+`<div class="nav-label">${p?'项目对话':'独立对话'}${p?ibutton('新的项目对话','new-project-thread',p.id,'plus'):''}</div>${S.threads.filter(t=>t.projectId===(p?.id||null)&&(t.messages.length||t.id===S.threadId)).slice(-8).reverse().map(t=>`<button class="recent ${S.threadId===t.id?'active':''}" data-action="thread" data-arg="${t.id}" title="${E(t.title)}">${E(t.title)}</button>`).join('')}<div class="nav-label">${p?'独立对话':''}</div>${p?S.threads.filter(t=>!t.projectId&&t.messages.length).slice(-3).map(t=>`<button class="recent" data-action="thread" data-arg="${t.id}">${E(t.title)}</button>`).join(''):''}`+html.slice(end);
 return html;};
composerHTML=function(home=false){let html=BASE.composerHTML(home);if(S.contextSelection)html=html.replace(`讨论：${E(S.contextSelection.title)} · v${S.contextSelection.revision} ${S.contextSelection.section?'／选中内容':''}`,`<button class="selection-open" data-action="selection-open">${E(S.contextSelection.title)} · v${S.contextSelection.revision}</button>`);return html;};
messageHTML=function(m){let html=BASE.messageHTML(m);const ref=m.artifactRefs?.find(r=>artifact(r.id)?.kind==='research');if(ref){const a=artifact(ref.id),v=revision(a,ref.revision);html=html.replace('<div class="message-actions">',`<div class="mini-research-grid">${v.data.sections.map(s=>`<button data-action="open-research-section" data-arg="${a.id}|${v.num}|${s.id}"><strong>${E(s.title)}</strong><small>${E(s.label)}</small></button>`).join('')}</div><div class="message-actions">`)}return html;};
contentHTML=function(a,v){let html=BASE.contentHTML(a,v);if(['strategy','research','notes','mh'].includes(a.kind)&&canWrite(a,false))html=`<div class="poster-toolbar">${button('编辑完整正文','edit-document',a.id+'|'+v.num,'sm','edit')}</div>`+html;return html.replace('结构示意图 · 非正式品牌物料 · 非印刷母版','目标型号官网产品图 · 屏幕预览 · 商业授权与印前条件待确认').replace('屏幕概念预览','屏幕预览');};
openCanvas=function(id,num=null,tab='content'){const a=artifact(id);if(!a)return;if(a.projectId&&a.projectId!==S.projectId){S.projectId=a.projectId;S.threadId=project(a.projectId).threadId}else if(!a.projectId&&S.projectId&&!project()?.contextArtifacts.includes(a.id)){S.projectId=null;const th=S.threads.find(t=>t.messages.some(m=>m.artifactIds?.includes(a.id)));if(th)S.threadId=th.id}MODAL=null;S.panelStack=[];S.canvas={id,num:num||a.pending||a.active,tab};S.view='chat';rememberCanvas();render();persist();};
function pathSet(obj,path,value){const keys=path.split('.'),last=keys.pop();keys.reduce((o,k)=>o[k],obj)[last]=value}
function finishEditor(a,base,data,note){const v=addRevision(a,data,note,base.refs);if(!v)return;delete S.panelDrafts[panelKey()];closeModal();S.canvas={id:a.id,num:v.num,tab:'content'};addMsg('assistant','已保存 v'+v.num+' 新候选，原采用版和固定提交保持不变。',{artifactIds:[a.id],artifactRefs:[{id:a.id,revision:v.num}]});render(true);persist();}
modifySelected=async function(instruction){const explicit=instruction.match(/(?:改为|改成|替换为|修改为)[：:\s“「"]*([\s\S]+)/)?.[1]?.replace(/[”」"]$/,'').trim();if(!explicit)return BASE.modifySelected(instruction);const sel=clone(S.contextSelection),a=artifact(sel?.artifactId||S.canvas?.id);if(!a||!canWrite(a))return;const base=revision(a,sel?.revision||S.canvas?.num||a.active),canvas=clone(S.canvas);return runWork('modify',async()=>{const d=clone(base.data);if(d.sections){const sec=d.sections.find(x=>x.id===sel?.section)||d.sections[0];sec.body=explicit;}else if(['pop','web','ecom'].includes(a.kind))d.headline=explicit;else if(a.kind==='mh'&&(!sel?.section||sel.section==='claim'))d.claim=explicit;else if(d.points){const point=d.points.find(p=>p.id===sel?.section)||d.points[0];point.benefit=explicit;}const v=addRevision(a,d,'明确文字修改：'+instruction,base.refs);S.canvas={id:a.id,num:v.num,tab:'content'};S.contextSelection=null;return {artifactIds:[a.id],text:'已按你的文字修改指定内容，形成 v'+v.num+' 候选。可比较后采用；其他成果仍引用原快照。'};});};
// Use existing source-backed photos. Keep supplied concept backgrounds explicitly labelled.
ASSET_FIXTURES.find(x=>x.id==='img-front').desc='目标型号官网正面照片，归档于 2026-09-09。商业使用授权待确认。';
Object.assign(ASSET_FIXTURES.find(x=>x.id==='img-open'),{name:'左侧产品图',view:'angle',type:'产品图',desc:'目标型号官网左侧视角照片。不是内部空间照片，商业授权待确认。'});
Object.assign(ASSET_FIXTURES.find(x=>x.id==='img-detail'),{name:'右侧产品图',view:'right',type:'产品图',desc:'目标型号官网右侧视角照片。不是取水器细节，商业授权待确认。'});
for(const x of ASSET_FIXTURES.slice(0,3))x.license='官网照片 · 演示可选';
ASSET_FIXTURES.find(x=>x.id==='img-scene').name='厨房背景 · 概念示意';
fridge=function(view='front',cls='fridge',standalone=false){const key=({open:'angle',detail:'right'})[view]||view;return `<svg xmlns="http://www.w3.org/2000/svg" class="${cls}" viewBox="${key==='front'?'800 250 1450 2500':'550 200 1900 2600'}" role="img" aria-label="SpaceMaster ${key==='angle'?'左侧':key==='right'?'右侧':'正面'}产品照片"><image href="${MERGED_ASSETS.images[key]||MERGED_ASSETS.images.front}" x="0" y="0" width="3000" height="3000" preserveAspectRatio="xMidYMid meet"/></svg>`;};
assetVisual=function(item){if(item?.dataURL)return BASE.assetVisual(item);return ['warm','cool'].includes(item?.view)?kitchen(item.view):fridge(item?.view)};
posterSvg=function(d,standalone=true){return BASE.posterSvg(d,standalone).replace('POP 示意预览','POP 屏幕预览').replace('OFFLINE DEMO / Imagen conceptual, no apta para impresión comercial.','VISTA PREVIA / Derechos comerciales y preimpresión pendientes.');};
makeContent=function(kind){const d=BASE.makeContent(kind);if(kind==='assets')d.note='3 张目标型号官网照片；厨房背景为概念示意。演示可用不等于商业使用授权。';if(['pop','web','ecom'].includes(kind)){const av=currentSource(byKind('assets')),items=av?.data.items||[];const chosen=items.map(assetItem).find(i=>i?.eligible&&(['front','angle','right'].includes(i.view)||i.type==='image'));d.image=chosen?.view||chosen?.id||'front';d.customImage=chosen?.dataURL||null;d.footer=PRODUCT.model+' · Vista previa';}return d;};
inspectContent=function(a,v){const check=BASE.inspectContent(a,v),d=v.data;const wrong=[...JSON.stringify(d).matchAll(/\b(\d{2,4})\s*L\b/g)].some(m=>m[1]!=='570')||(a.kind==='pop'&&!d.footer.includes(PRODUCT.model));if(wrong){check.passed=false;check.findings[0]={title:'目标型号与容量',ok:false,detail:'内容与目标型号的 570 L 或型号标识不一致，请核对资料。'};}return check;};
adopt=function(id,num){const a=artifact(id);if(!a||!canWrite(a))return;num=num||a.pending||a.active;if(!revision(a,num))return;const t=S.tasks.find(t=>t.id===a.taskId);if(t?.status==='done'&&t.maturity==='approved'){if(approvalFor(a,num))return toast('这个版本已经批准，原交付保持完成。');const next={...clone(t),id:uid('task'),name:t.name+' · 后续改版',status:'working',revision:1,previousTaskId:t.id};S.tasks.push(next);a.taskId=next.id;}return BASE.adopt(id,num);};
const baseRunSpec=runSpec;
runSpec=function(kind){const spec=baseRunSpec(kind);if(kind==='assets')for(const step of spec.steps){if(step[4]?.illustrationOnly){delete step[4].illustrationOnly;step[4].sourceBackedProductPhotos=3;step[4].conceptBackgrounds=2;}}return spec;};
exportHTML=function(a,v,label){return BASE.exportHTML(a,v,label).replace('产品图为概念示意','产品图来自目标型号官网归档，厨房背景为概念示意')};
versionFiles=function(a,v,label){const files=BASE.versionFiles(a,v,label);files['asset-provenance.txt']='SpaceMaster MDRS761MYM45A / 2026-09-09 官网图片归档。\n三张实物产品照片：正面、左侧、右侧。厨房背景为 v4 提供的概念示意。\n商业图片授权与印前条件待确认。\nhttps://www.midea.com/mx/refrigeracion/sbs/refrigerador-side-by-side-spacemaster-basalt-gray-21-pies-cubicos.mdrs761mym45a';return files;};
// Single engine, multiple conversations: asynchronous results stay with their captured run.
runWork=function(kind,done,opts){const target={pid:S.projectId,tid:S.threadId,actor:S.actor};return BASE.runWork(kind,async r=>{const visible={pid:S.projectId,tid:S.threadId,actor:S.actor,canvas:clone(S.canvas),view:S.view};S.projectId=target.pid;S.threadId=target.tid;S.actor=target.actor;try{return await done(r)}finally{if(visible.tid!==target.tid){S.projectId=visible.pid;S.threadId=visible.tid;S.actor=visible.actor;S.canvas=visible.canvas;S.view=visible.view}}},opts)};
handle=async function(action,arg=''){
  if(action==='panel-close'||action==='modal-close'){closeModal();return}
  if(action==='panel-back'){capturePanel();const prior=S.panelStack.pop();if(prior){MODAL=prior;render();renderModal();persist()}else closeModal();return}
  if(action==='canvas-switch'){const[id,n]=arg.split('|');openCanvas(id,+n);return}
  if(action==='canvas-tab-close'){const[id,n]=arg.split('|');S.openCanvases=S.openCanvases.filter(c=>!(c.id===id&&c.num===+n));if(S.canvas?.id===id&&S.canvas.num===+n){S.canvas=S.openCanvases.at(-1)?{...S.openCanvases.at(-1),tab:'content'}:null;}render();persist();return}
  if(action==='new-project-thread'){closeModal();newChat(arg);return}
  if(action==='selection-open'){const s=S.contextSelection;if(s)openCanvas(s.artifactId,s.revision);return}
  if(action==='open-research-section'){const[id,n,sec]=arg.split('|');openCanvas(id,+n);requestAnimationFrame(()=>{document.querySelector(`[data-action="select-section"][data-arg="${id}|${n}|${sec}"]`)?.closest('.section')?.scrollIntoView({block:'start'})});return}
  if(action==='edit-document'){showModal('edit-document',arg);return}
  if(action==='save-document'){const[id,n]=arg.split('|'),a=artifact(id),base=revision(a,+n);if(!canWrite(a))return;const data=clone(base.data);for(const el of document.querySelectorAll('[data-doc-path]')){if(!el.value.trim())return toast('请保留必要正文。',true);pathSet(data,el.dataset.docPath,el.value.trim())}finishEditor(a,base,data,'直接编辑完整正文');return}
  if(action==='restore-backup'){const el=document.createElement('input');el.type='file';el.accept='.json';el.onchange=async()=>{try{const data=JSON.parse(await el.files[0].text());if(data.schema!==APP_VERSION||!['threads','projects','tasks','artifacts','runs'].every(k=>Array.isArray(data[k])))throw Error('请选择 SpaceMaster Demo V6 演示备份');for(const a of data.artifacts)if(!Array.isArray(a.versions)||!a.versions.length)throw Error('备份成果版本不完整');window.pendingBackup=data;showModal('restore-confirm')}catch(e){toast(e.message,true)}};el.click();return}
  if(action==='restore-confirm'){CANCEL_TOKEN++;S=window.pendingBackup;delete window.pendingBackup;S.runId=null;S.paused=false;if(S.auto)S.auto.active=false;S.runs.filter(r=>r.status==='running').forEach(r=>r.status='interrupted');Object.keys(DRAFTS).forEach(k=>delete DRAFTS[k]);Object.assign(DRAFTS,S.composerDrafts||{});MODAL=null;S.panelStack=[];render();persist();return}
  if(action==='save-material'||action==='save-point'){const key=panelKey();await BASE.handle(action,arg);delete S.panelDrafts[key];persist();return}
  if(action==='new-chat'&&S.runId){closeModal();newChat();return}
  if(['project','thread','nav','close-canvas'].includes(action)){capturePanel();MODAL=null;S.panelStack=[];const root=dockRoot();root.innerHTML='';document.body.appendChild(root)}
  return BASE.handle(action,arg);
};
function scheduleText(){const generation=++renderGeneration;textObserver?.disconnect();textMutations?.disconnect();document.fonts.ready.then(()=>{if(generation!==renderGeneration)return;const nodes=[...document.querySelectorAll('.assistant-body,.thought,.result-summary,.doc-lead')],cache=new WeakMap();let pending=false;const layoutAll=()=>{pending=false;if(generation!==renderGeneration)return;nodes.forEach(el=>{if(!el.isConnected||!el.clientWidth)return;const cs=getComputedStyle(el),width=el.clientWidth-parseFloat(cs.paddingLeft||0)-parseFloat(cs.paddingRight||0),text=el.textContent,c=cache.get(el);if(c?.text===text&&c.width===width)return;const prepared=Pretext.prepare(text,cs.font||`${cs.fontSize} ${cs.fontFamily}`,{whiteSpace:'pre-wrap'}),m=Pretext.layout(prepared,Math.max(width,1),parseFloat(cs.lineHeight)||22);el.style.minHeight=(m.height+parseFloat(cs.paddingTop||0)+parseFloat(cs.paddingBottom||0))+'px';el.dataset.pretextLines=m.lineCount;cache.set(el,{text,width})})};const queue=()=>{if(!pending){pending=true;requestAnimationFrame(layoutAll)}};textObserver=new ResizeObserver(queue);textMutations=new MutationObserver(queue);nodes.forEach(n=>{textObserver.observe(n);textMutations.observe(n,{characterData:true,subtree:true,childList:true})});queue();});}
document.addEventListener('input',e=>{if(e.target.id==='composer'){S.composerDrafts={...DRAFTS};BASE.persist()}if(e.target.closest('#modal-root')&&!isBlockingModal(MODAL?.kind)){capturePanel();BASE.persist()}});
document.addEventListener('change',e=>{if(e.target.closest('#modal-root')){capturePanel();BASE.persist()}});
document.addEventListener('pointerdown',e=>{if(!e.target.matches('.work-resizer'))return;e.preventDefault();const main=document.querySelector('.main'),rect=main.getBoundingClientRect();e.target.setPointerCapture(e.pointerId);const move=ev=>{S.workbenchWidth=Math.max(40,Math.min(72,(rect.right-ev.clientX)/rect.width*100));main.style.setProperty('--workbench-width',S.workbenchWidth+'%')};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);persist()};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)});
document.addEventListener('keydown',e=>{if(e.target.matches('.work-resizer')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();S.workbenchWidth=Math.max(40,Math.min(72,S.workbenchWidth+(e.key==='ArrowLeft'?2:-2)));document.querySelector('.main').style.setProperty('--workbench-width',S.workbenchWidth+'%');persist()}});
if(panelRestore&&!isBlockingModal(panelRestore.kind))MODAL=panelRestore;
window.LilithMerged={version:APP_VERSION,get state(){return S},get panel(){return MODAL},isBlockingModal};
