import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';

const root=path.resolve(import.meta.dirname,'../..'),out=path.join(root,'output/demo-spacemaster-v6');
const sha=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const evidence=JSON.parse(fs.readFileSync(path.join(out,'qa-v62/checks.json'),'utf8'));
const entry=path.join(root,'Lilith SpaceMaster Demo V6.html');
if(evidence.version!=='6.2.0'||evidence.checks.some(x=>!x.ok)||!evidence.domainTestsPassed||sha(entry)!==evidence.htmlSha256)throw Error('Run current V6.2 verification before packaging.');
for(const [file,hash] of Object.entries(evidence.sourceHashes))if(sha(path.join(root,file))!==hash)throw Error('Source changed since verification: '+file);
const name='Lilith SpaceMaster V6.2',releaseRoot=path.join(out,'release-v62'),dest=path.join(releaseRoot,name);
fs.mkdirSync(dest,{recursive:true});
fs.copyFileSync(entry,path.join(dest,'Lilith SpaceMaster Demo V6.html'));
fs.cpSync(path.join(root,'public/demo-spacemaster-v6'),path.join(dest,'public/demo-spacemaster-v6'),{recursive:true});
fs.copyFileSync(path.join(out,'V6.2-修复与验证.md'),path.join(dest,'V6.2-修复与验证.md'));
fs.copyFileSync(path.join(out,'V6.2-用户流程.md'),path.join(dest,'使用说明与用户流程.md'));
fs.mkdirSync(path.join(dest,'qa-v62'),{recursive:true});
for(const file of ['checks.json','domain-tests.tap'])fs.copyFileSync(path.join(out,'qa-v62',file),path.join(dest,'qa-v62',file));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'public/demo-spacemaster-v6/manifest.json'),'utf8'));
for(const f of manifest)if(sha(path.join(dest,'public/demo-spacemaster-v6',f.file))!==f.sha256)throw Error('Release original hash mismatch: '+f.id);
fs.writeFileSync(path.join(dest,'qa-v62/release-manifest.json'),JSON.stringify({version:'6.2.0',htmlSha256:sha(entry),originalHashes:manifest.map(f=>({id:f.id,file:f.file,sha256:f.sha256})),domainTestsPassed:evidence.domainTestsPassed,offlineOpen:'not_run_browser_policy',visual:'not_run'},null,2));
const archive=path.join(out,name+'.zip'),temp=path.join(out,name+'.building.zip');
if(fs.existsSync(temp))fs.unlinkSync(temp);
const zip=spawnSync('zip',['-qr',temp,name],{cwd:releaseRoot,encoding:'utf8'});if(zip.status)throw Error(zip.stderr);
const test=spawnSync('unzip',['-t',temp],{encoding:'utf8'});if(test.status)throw Error(test.stdout);
fs.renameSync(temp,archive);
const result={version:'6.2.0',entry:path.join(dest,'Lilith SpaceMaster Demo V6.html'),archive,bytes:fs.statSync(archive).size,htmlSha256:sha(entry),zipSha256:sha(archive),originalHashes:manifest.length,zipIntegrity:'passed',offlineOpen:'not_run_browser_policy',visual:'not_run'};
fs.writeFileSync(path.join(out,'qa-v62/package-checks.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
