import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
const out='/Users/dingcheng/Coding-Project/02-key-project/Lilith-原型/output/demo-spacemaster-v6';
const setup=`(()=>{
S=makeState();MODAL=null;S.inspectorOpen=false;Object.keys(DRAFTS).forEach(k=>delete DRAFTS[k]);const p=S.projects[0];S.projectId=p.id;S.threadId=p.threadId;p.scopeConfirmed=true;
S.tasks=rulesFor(['web','retail'],'Hero').filter(r=>r.category!=='推荐').map((r,i)=>({...r,id:'shell-task-'+i,projectId:p.id,status:'todo',assignee:'lin',reviewer:'reviewer',revision:1}));
for(const t of S.tasks){const a=newArtifact(t.kind,makeContent(t.kind),p.id,sourceRefs(BATCH_DEPS[t.kind]||[],p.id));t.artifactId=a.id;t.status='draft_ready';}
addMsg('user','准备墨西哥上市的第一轮内容。');S.view='tasks';render();document.querySelector('#toast').hidden=true;return {rows:document.querySelectorAll('.task-row').length,nested:document.querySelectorAll('.task-row .task-row').length,siblings:document.querySelectorAll('.task-cards>.task-row').length};})()`;
const test=`(async()=>{
const results=[];function check(name,ok){results.push({name,ok});if(!ok)throw Error(name)}
check('six task cards are independent siblings',document.querySelectorAll('.task-cards>.task-row').length===6&&!document.querySelector('.task-row .task-row'));
check('project examples use three product categories',new Set(S.projects.map(p=>p.category)).size>=3&&S.projects.some(p=>p.category==='洗碗机')&&S.projects.some(p=>p.category==='电饭煲'));
for(const status of ['draft_ready','changes_requested','todo','working','done']){S.tasks.forEach(t=>t.status=status);render();check('flat cards for '+status,document.querySelectorAll('.task-cards>.task-row').length===6&&!document.querySelector('.task-row .task-row'))}S.tasks.forEach(t=>t.status='draft_ready');
check('project groups own their conversation buttons',S.projects.every(p=>{const group=document.querySelector('[data-project-id="'+p.id+'"]');return group?.querySelector('.project-conversations [data-action="thread"]')}));
const pid=S.projectId;await handle('project-toggle',pid);check('project collapse preserves active conversation',document.querySelector('#threads-'+pid).hidden&&S.projectId===pid);await handle('project-toggle',pid);await handle('new-project-thread',pid);check('new conversation is nested in its own project',thread().projectId===pid&&document.querySelector('[data-project-id="'+pid+'"] [data-arg="'+S.threadId+'"]').closest('.project-conversations'));
const comp=document.querySelector('.composer-dock,.home-input');check('project context is above the input frame',!!comp.querySelector('.composer-project-context')&&comp.querySelector('.composer-frame').previousElementSibling.classList.contains('composer-project-context'));
check('attach control precedes mode control',!!(document.querySelector('.composer-tools [data-action="attach"]').compareDocumentPosition(document.querySelector('#work-mode'))&Node.DOCUMENT_POSITION_FOLLOWING));
check('composer has no persistent mode explanation or folder',!comp.querySelector('.input-note')&&!comp.querySelector('.composer-tools [data-action="context"]'));
const prior=workMode();await handle('mode-open');check('mode switching opens a focused dialog',!!document.querySelector('.modal-overlay')&&!!document.querySelector('[name="next-work-mode"]'));closeModal();check('cancel mode dialog changes no mode or plan',workMode()===prior&&S.plans.length===0);
await handle('mode-open');document.querySelector('[name="next-work-mode"][value="yolo"]').checked=true;await handle('mode-apply');check('autonomous mode has distinct style and plain name',workMode()==='yolo'&&document.querySelector('#work-mode').classList.contains('mode-yolo')&&document.querySelector('#work-mode').innerText.includes('自主完成')&&!document.querySelector('#work-mode').innerText.includes('YOLO'));
await handle('context',pid);check('project background uses compact inspector rather than full detail form',document.querySelector('.work-inspector')?.getBoundingClientRect().width<=380&&!MODAL&&!!document.querySelector('.project-facts')&&!document.querySelector('.inspector-body input'));
check('no bottom workspace strip',!document.querySelector('footer.workspace-status')&&!document.querySelector('.demo-bar'));
await handle('project-info-edit',pid);document.querySelector('#project-info-goal').value='为墨西哥上市完成渠道内容。';await handle('project-info-save',pid);check('project facts edit saves to project',project(pid).goal==='为墨西哥上市完成渠道内容。');await handle('inspector-close');check('inspector can be folded away',!document.querySelector('.work-inspector'));
check('brand wordmark has requested weight',getComputedStyle(document.querySelector('.brand-lockup .wordmark')).fontWeight==='600');
check('capability entry uses connector icon',document.querySelector('.primary-nav [data-action="capabilities"] path').getAttribute('d')===ICONS.plug);
check('settings entry replaces redundant badge',document.querySelector('.sidebar-bottom [data-action="settings"]').innerText==='设置'&&!document.querySelector('.workspace-badge'));
S.view='library';S.canvas=null;render();check('artifact cards use view-details wording',!document.querySelector('.library-grid').innerText.includes('工作面')&&document.querySelector('.library-grid').innerText.includes('查看详情'));
const cards=[...document.querySelectorAll('.library-grid>.result-card')],rows=new Map();for(const c of cards){const y=Math.round(c.getBoundingClientRect().top),foot=c.querySelector('.result-foot').getBoundingClientRect().top;if(!rows.has(y))rows.set(y,[]);rows.get(y).push(foot)}check('artifact footers align per row',[...rows.values()].every(ys=>Math.max(...ys)-Math.min(...ys)<2));
check('artifact status labels do not wrap',cards.every(c=>getComputedStyle(c.querySelector('.tag')).whiteSpace==='nowrap'));
await handle('nav','files');check('files include external search source category',document.querySelector('.external-source-card')?.innerText.includes('外部搜索信源'));await handle('external-sources');document.querySelector('#external-title').value='竞品信息网址校验';document.querySelector('#external-url').value='javascript:alert(1)';await handle('external-source-save');check('external sources reject unsafe links',S.externalSources.length===0);document.querySelector('#external-url').value='https://example.com/product';await handle('external-source-save');check('external source retains URL and verification status',S.externalSources.length===1&&S.externalSources[0].status==='待核验'&&S.externalSources[0].url==='https://example.com/product');closeModal();S.view='library';render();
await handle('content-library');check('Content Library entry offers explicit push selection',document.querySelector('.dock-host').innerText.includes('推送到 Content Library')&&document.querySelectorAll('[data-push-id]').length===6);
check('unconfirmed drafts cannot be silently pushed',[...document.querySelectorAll('[data-push-id]')].every(n=>n.disabled));const a=S.artifacts.find(a=>a.kind==='strategy');closeModal();adopt(a.id,1);await handle('content-library');document.querySelector('[data-push-id="'+a.id+'"]').checked=true;await handle('content-library-push');check('push stores a fixed simulated version without approval',S.libraryPushes.length===1&&S.libraryPushes[0].revision===1&&S.libraryPushes[0].status==='received'&&S.libraryPushes[0].simulation&&S.submissions.length===0);await handle('content-library-push');check('push is not duplicated',S.libraryPushes.length===1);closeModal();
showModal('role');const luminance=css=>{const channels=css.match(/[\\d.]+/g).slice(0,3).map(Number).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4});return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722};check('role choices have readable foreground and background',[...document.querySelectorAll('.choice')].every(el=>{const cs=getComputedStyle(el),fg=luminance(cs.color),bg=luminance(cs.backgroundColor);return (Math.max(fg,bg)+.05)/(Math.min(fg,bg)+.05)>=4.5}));closeModal();
const pop=S.artifacts.find(a=>a.kind==='pop'),sub={id:'shell-review',artifactId:pop.id,projectId:pid,taskId:pop.taskId,title:pop.title,revision:1,snapshot:clone(revision(pop,1)),requirement:{text:'检查本次门店 POP 的文案与型号。'},submitter:'lin',reviewer:'reviewer',status:'pending'};S.submissions.push(sub);showModal('review',sub.id);check('review distinguishes actual copy from reference claims',!!document.querySelector('.review-material-copy')&&!document.querySelector('.review-material-copy .code')&&document.querySelector('.review-material-copy').innerText.includes('本次物料文案')&&document.querySelector('.review-material-copy summary').innerText.includes('参考卖点'));closeModal();
const plan=discussPlan('确认这一轮上市内容。','plan');plan.status='confirmed';showModal('plan',plan.id);const box=document.querySelector('.plan-item input:checked'),label=document.querySelector('.plan-item strong'),ico=document.querySelector('.plan-item .icon');check('locked plan checkbox stays blue',getComputedStyle(box).backgroundColor===getComputedStyle(document.documentElement).getPropertyValue('--brand').trim()||getComputedStyle(box).appearance==='none'&&getComputedStyle(box).opacity==='1');check('plan icon and title align',Math.abs((ico.getBoundingClientRect().top+ico.getBoundingClientRect().height/2)-(label.getBoundingClientRect().top+label.getBoundingClientRect().height/2))<3);closeModal();
const savedProject=S.projectId;goProject(S.projects.find(p=>p.category==='洗碗机').id);const countArtifacts=S.artifacts.length;await generate('strategy');check('different product does not inherit fridge facts',MODAL?.kind==='product-intake'&&S.artifacts.length===countArtifacts&&!document.querySelector('.dock-host').innerText.includes('570'));closeModal();goProject(savedProject);
const mh=S.artifacts.find(a=>a.kind==='mh');openCanvas(mh.id,1);const tabCount=S.openCanvases.length,inline=document.querySelector('.point-inline');check('selling point expands within the current Message House',!!inline&&!document.querySelector('.pillar [data-action="point-detail"]'));inline.open=true;inline.dispatchEvent(new Event('toggle'));render();check('expanded point survives render without adding tabs',S.openCanvases.length===tabCount&&!MODAL&&document.querySelector('.point-inline').open);S.canvas.tab='sources';render();check('knowledge sources use independent cards',!!document.querySelector('.reference-grid>.reference-card')&&!document.querySelector('.reference-sections .ref-row'));
S.view='tasks';S.inspectorOpen=false;render();document.querySelector('#toast').hidden=true;return results;
})()`;
const layout=`(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,overflowing:[...document.querySelectorAll('.view-content,.library-grid,.result-card,.task-card,.composer-frame,.work-inspector,.dock-host')].filter(e=>e.clientWidth&&e.scrollWidth>e.clientWidth+3).map(e=>e.className),nested:document.querySelectorAll('.task-row .task-row').length}))()`;
const args=['run','/Users/dingcheng/.gstack/repos/gstack/bin/gstack-render.ts',out+'/finalized.html','--timeout','120000','--eval',setup,'--out',out+'/v52-task-structure.json','--eval',test,'--out',out+'/v52-shell-result.json','--screenshot',out+'/v52-tasks-desktop.jpg','--width','1888','--height','1324','--jpeg','--eval',layout,'--out',out+'/v52-tasks-layout.json','--eval',`(()=>{S.view='library';render();return true})()`,'--screenshot',out+'/v52-library-desktop.jpg','--width','1888','--height','1324','--jpeg','--eval',`(()=>{showModal('role');return true})()`,'--screenshot',out+'/v52-role-desktop.jpg','--width','1440','--height','960','--jpeg','--eval',layout,'--out',out+'/v52-split-layout.json','--eval',`(()=>{closeModal();S.view='chat';openInspector('project',S.projectId);return true})()`,'--screenshot',out+'/v52-inspector-desktop.jpg','--width','1440','--height','960','--jpeg','--eval',`(()=>{S.inspectorOpen=false;render();openModeDialog('yolo');return true})()`,'--screenshot',out+'/v52-mode-desktop.jpg','--width','1440','--height','960','--jpeg','--screenshot',out+'/v52-mode-mobile.jpg','--width','375','--height','812','--jpeg','--eval',`(()=>{closeModal();S.inspectorOpen=false;S.view='tasks';render();return true})()`,'--screenshot',out+'/v52-tasks-mobile.jpg','--width','375','--height','812','--jpeg','--eval',layout,'--out',out+'/v52-mobile-layout.json','--eval',`(()=>{S.projectId=null;newChat();S.inspectorOpen=false;render();return true})()`,'--screenshot',out+'/v52-home-desktop.jpg','--width','1440','--height','1100','--jpeg'];
const r=spawnSync('bun',args,{encoding:'utf8',timeout:145000});fs.writeFileSync(out+'/v52-verification.log',(r.stdout||'')+(r.stderr||''));console.log(r.stdout);console.error(r.stderr);if(r.status!==0||/PAGE_ERRORS=\[(?!\])/.test(r.stdout))process.exit(1);
const checks=JSON.parse(fs.readFileSync(out+'/v52-shell-result.json','utf8'));if(checks.some(c=>!c.ok))throw Error('Shell checks failed');
for(const key of ['tasks','split','mobile']){const l=JSON.parse(fs.readFileSync(out+'/v52-'+key+'-layout.json','utf8'));if(l.overflow||l.overflowing.length||l.nested)throw Error('Layout failure: '+JSON.stringify(l))}
console.log(JSON.stringify({checks:checks.length,passed:true}));
