let CANCEL_TOKEN=0;
function runSpec(kind){const specs={
 research:{name:'理解墨西哥的使用场景',module:'research',sources:['P01','R01'],thought:'先建立比较维度，不先写确定结论。厨房升级与食品安排只是工作假设；缺少当地竞品原始数据，就保留研究缺口，不填造排名。',steps:[['research.search','检索市场与使用场景','MCP · 模拟',{market:'MX',category:'refrigerator',focus:'kitchen upgrade'},{documents:3,verifiedConsumerStudy:false}],['evidence.read','区分事实、假设和缺口','MCP · 模拟',{sources:['P01','R01']},{facts:1,hypotheses:2,competitorData:'missing'}]]},
 create:{name:'建立项目上下文',module:'workspace',sources:['P01','T01'],thought:'先建立可撤销的项目空间，再查询适用交付规则。创建空间无需重复许可；交付清单涉及本次范围，需要向你解释后确认。',steps:[['project.create','建立产品上市空间','Lilith 原生 · 浏览器实现',{product:'SpaceMaster',market:'MX'},{contextSpace:'ready_to_create',commit:'on successful run completion',formalCommitment:false}],['scope.resolve','匹配产品与渠道交付要求','Lilith 原生 · 浏览器实现',{category:'冰箱',tier:'Hero',channels:['web','retail'],ruleVersion:2},{required:3,conditional:3,recommended:1}]]},
 strategy:{name:'形成产品策略',module:'gtm',sources:['P01','P02','R01','B01'],thought:'把产品事实与场景假设分开。优先表达空间组织与厨房整合，不从功能名称推导节能百分比。官网与门店共享价值，表达深度不同。',steps:[['product.read','读取目标型号资料','MCP · 模拟',{model:PRODUCT.model,market:'MX'},{capacity:'570 L',scope:'MX',source:'P01'}],['knowledge.search','调用市场与品牌知识','MCP · 模拟',{ids:['R01','B01']},{hypotheses:3,brandRules:4}],['strategy.compose','组织受众、定位与价值优先级','专业能力 · 模拟',{method:'Product Strategy v2'},{sections:4,unsupportedClaims:0}]]},
 fabe:{name:'建立 FABE 价值体系',module:'gtm',sources:['P01','P02','X01'],thought:'570 L 与薄壁设计共同支持空间组织；Counter Depth 与尺寸共同支持安装讨论。证据只能证明它实际支持的内容，不能证明所有厨房都适配。',steps:[['evidence.lookup','定位每个 Feature 的依据','MCP · 模拟',{model:PRODUCT.model},{evidence:['P01','P02'],excluded:['X01']}],['fabe.compose','构建功能到利益的关系','专业能力 · 模拟',{method:'FABE Value Design v2'},{themes:3,sharedFeatures:true}],['content.check','检查推导与证据绑定','MCP · 模拟',{checks:['scope','evidence','unsupported-numbers']},{unsupportedClaims:0,warnings:['installation requirements']}]]},
 mh:{name:'编写本地化 Message House',module:'gtm',sources:['B01','C01','P02'],thought:'沿用选中的价值主题，用墨西哥西班牙语形成主张、利益与长短描述。可引用已有草稿，不把上游批准当作开始写作的条件。',steps:[['artifact.read','读取指定 FABE 草稿版本','Lilith 原生 · 浏览器实现',{source:'fabe',binding:'fixed revision'},{upstreamApprovalRequired:false}],['mh.compose','组织信息屋与表达层级','专业能力 · 模拟',{language:'es-MX',method:'Message House v2'},{claims:1,pillars:3,longAndShort:true}],['localization.check','检查语言与品牌表达','MCP · 模拟',{market:'MX',source:'C01'},{locale:'es-MX',numericClaims:'unchanged'}]]},
 assets:{name:'找到适合当前用途的素材',module:'asset',sources:['P01','B01'],thought:'先核对型号和使用范围，再看画面是否合适。参考款与授权待确认的图可以留在搜索结果里，但不能混进本次交付集合。',steps:[['assets.search','检索产品、功能与场景图','MCP · 模拟',{model:PRODUCT.model,types:['product','feature','scene']},{matches:6,illustrationOnly:true}],['assets.inspect','检查型号与可用范围','MCP · 模拟',{matches:6},{eligible:4,excluded:2,commercialRightsVerified:false}]]},
 pop:{name:'为线下门店制作 POP',module:'production',sources:['C01','B01'],thought:'用一条主张建立第一眼识别，再保留型号与可核对支撑。把文案、图片与模板作为独立输入绑定，方便后续改稿与版本追溯。',steps:[['artifact.read','读取 MH 与素材固定版本','Lilith 原生 · 浏览器实现',{sources:['mh','assets']},{draftSourcesAllowed:true}],['material.compose','生成门店 POP 候选','MCP · 模拟',{channel:'retail',language:'es-MX',template:'product'},{formats:['svg','html'],printReady:false}],['design.preview','渲染产品与文案预览','浏览器渲染',{size:[600,900]},{rendered:true,externalCanva:false}]]},
 web:{name:'制作官网产品页内容',module:'production',sources:['C01','B01'],thought:'官网允许更充分的解释。保留三组价值、安装提醒和产品型号，让页面与门店物料共享事实，但不使用同一套版式。',steps:[['artifact.read','读取 MH 与素材','Lilith 原生 · 浏览器实现',{sources:['mh','assets']},{fixedRefs:true}],['material.compose','生成官网页面草稿','MCP · 模拟',{channel:'web',locale:'es-MX'},{hero:1,featureSections:3,published:false}]]},
 ecom:{name:'准备电商商品内容',module:'production',sources:['P01','C01'],thought:'电商内容保留清晰标题、卖点与型号规格。这里只制作内容，不模拟上架，不生成虚构价格或促销。',steps:[['artifact.read','读取产品与 MH','Lilith 原生 · 浏览器实现',{sources:['mh']},{fixedRefs:true}],['material.compose','组织商品内容草稿','MCP · 模拟',{channel:'ecommerce'},{published:false,price:null}]]},
 modify:{name:'根据反馈形成新建议',module:'gtm',sources:['B01','C01'],thought:'修改只作用于这一次绑定的成果版本。先保留原文和来源，再形成新候选；采用之前，不覆盖你已经确认的内容。',steps:[['artifact.read','读取用户选中的成果版本','Lilith 原生 · 浏览器实现',{binding:'selected revision'},{versionBound:true}],['artifact.propose','生成新的完整候选','专业能力 · 模拟',{operation:'revise'},{overwritesCurrent:false,keepsHistory:true}]]},
 check:{name:'检查当前物料是否可提交',module:'check',sources:['P01','B01','C01'],thought:'分别检查产品事实、品牌表达和渠道适用性。AI 检查是辅助，不是正式批准；审核人仍然决定是否接受这个固定版本。',steps:[['content.check','检查事实、品牌与渠道','MCP · 模拟',{checks:['facts','brand','channel']},{findings:'evaluated against fixture rules',humanApproval:false}]]},
 notes:{name:'整理成可复用的工作摘要',module:'workspace',sources:[],thought:'按用户输入整理决定、负责人和下一步，不补写没有提供的会议结论。结果可以先独立保存，之后再引用到项目。',steps:[['document.organize','整理本地输入的资料','浏览器规则化整理',{mode:'extract and structure'},{modelCall:false,createsArtifact:true}]]},
 ask:{name:'解释当前工作与依据',module:'gtm',sources:['P01','R01'],thought:'读取当前讨论对象及其版本，只回答你的问题。不产生新成果版本，不移动正式指针，也不推进下游任务。',steps:[['artifact.read','读取讨论对象与来源','Lilith 原生 · 浏览器实现',{mode:'read-only'},{createsRevision:false}]]}
};return clone(specs[kind]||specs.ask);}
async function wait(ms,token=CANCEL_TOKEN){let remaining=ms;while(remaining>0){if(token!==CANCEL_TOKEN)throw new Error('CANCELLED');if(S.paused){await new Promise(r=>setTimeout(r,45));continue}const speed=S.settings.speed*(window.__LILITH_QA_TIME_SCALE||1);const step=Math.min(40,remaining/speed);await new Promise(r=>setTimeout(r,Math.max(1,step)));remaining-=step*speed;}}
async function typeText(obj,key,text,selector,token){obj[key]='';let i=0;while(i<text.length){await wait(38,token);const chunk=window.__LILITH_QA_TIME_SCALE?4:1;obj[key]=text.slice(0,i+=chunk);let el=document.querySelector(selector);if(el)el.textContent=obj[key];}persist();}
async function runWork(kind,onDone,opts={}){if(S.runId){toast('Lilith 正在处理一项工作。可以暂停、取消或等它完成。');return null}const spec=runSpec(kind),token=CANCEL_TOKEN,pid=S.projectId,tid=S.threadId,actor=S.actor;const r={id:uid('run'),kind,name:spec.name,actor,projectId:pid,threadId:tid,status:'running',started:now(),module:spec.module,sources:spec.sources,thought:'',events:spec.steps.map((x,i)=>({id:uid('call'),seq:i+1,name:x[0],label:x[1],transport:x[2],input:x[3],output:null,plannedOutput:x[4],status:'pending'})),retry:opts.retry||kind,savedSelection:clone(S.contextSelection),savedCanvas:clone(S.canvas)};S.runs.push(r);S.runId=r.id;const msg=addMsg('assistant','',{runId:r.id},tid);render(true);persist();try{for(let i=0;i<r.events.length;i++){let e=r.events[i];e.status='running';e.started=now();render(true);await wait(950,token);if(i===0)await typeText(r,'thought',spec.thought,`[data-thought="${r.id}"]`,token);await wait(850,token);if(typeof prepareImageStep==='function')await prepareImageStep(e,r,token);e.status='done';e.output=clone(e.plannedOutput);e.ended=now();render(true);persist();}if(token!==CANCEL_TOKEN)throw new Error('CANCELLED');let output=await onDone(r);r.status='done';r.ended=now();msg.artifactIds=output?.artifactIds||[];msg.artifactRefs=msg.artifactIds.map(id=>{const a=artifact(id);return{id,revision:a.pending||a.active}});msg.action=output?.action||null;msg.scopeProject=output?.scopeProject||null;msg.check=output?.check||null;msg.text='';render(true);await typeText(msg,'text',output?.text||'工作已完成，结果已保存。',`[data-message-text="${msg.id}"]`,token);S.runId=null;render(true);persist();return r;}catch(e){r.status=e.message==='CANCELLED'?'cancelled':'failed';r.ended=now();r.error=e.message;r.events.filter(x=>x.status==='running').forEach(x=>x.status=r.status);if(S.runId===r.id)S.runId=null;msg.text=e.message==='CANCELLED'?'本次执行已取消。已保存的成果和批准版本保持不变，可重试这项工作。':'本次执行未完成：'+e.message+'。已有成果保持不变。';log('执行未完成',r.name+' · '+r.status,pid);render(true);return null;}}
async function createProject(){return runWork('create',async()=>{let p=S.projects.find(x=>x.model===PRODUCT.model&&x.market==='MX');if(!p){p={id:uid('project'),name:'SpaceMaster 上市计划',model:PRODUCT.model,category:'冰箱',tier:'Hero',market:'MX',markets:['MX'],channels:['web','retail'],language:'es-MX',goal:'在墨西哥形成产品价值、可用素材和官网／门店物料。',owner:'lin',scopeConfirmed:false,ruleVersion:2,threadId:uid('chat'),created:now(),contextArtifacts:[]};S.projects.push(p);S.threads.push({id:p.threadId,title:'SpaceMaster 上市协作',projectId:p.id,messages:[],created:now()});log('已创建项目空间',p.name+' · 墨西哥 · 官网 / 门店',p.id)}return{scopeProject:p.id,action:'enter-project',text:'已建立 SpaceMaster 上市空间，关联墨西哥产品与市场资料。根据冰箱 · Hero · 官网／门店的演示规则，匹配到 6 项交付；另外 1 项研究报告是可选建议。\n\n空间已创建。接下来只需确认本次交付范围，不需要重复批准创建动作。'};});}
function confirmScope(pid,selectedKinds){let p=project(pid);if(!p)return;const rules=rulesFor(p.channels,p.tier);const picked=selectedKinds||rules.filter(r=>r.category!=='推荐').map(r=>r.kind);const valid=rules.filter(r=>picked.includes(r.kind));const required=rules.filter(r=>r.category==='必需');if(required.some(r=>!picked.includes(r.kind)))return toast('基础必需项不可在本演示中静默删除。',true);for(const r of valid){if(!taskFor(r.kind,pid)){S.tasks.push({id:uid('task'),projectId:pid,kind:r.kind,domain:r.domain,name:r.name,maturity:r.maturity,requirement:r.requirement,reason:r.reason,ruleVersion:p.ruleVersion,assignee:'lin',reviewer:'reviewer',status:'todo',revision:1,artifactId:null})}}
p.scopeConfirmed=true;p.scope=clone(valid);goProject(pid,false);addMsg('assistant','交付范围已确认。我会先整理产品价值，再准备素材和渠道物料。你可以随时从任一有输入的工作开始；不需要等全部上游批准。',{action:'generate-strategy'});log('已确认交付范围',valid.length+' 项交付 · 规则 v'+p.ruleVersion,pid);closeModal();render(true);persist();}
async function generate(kind){const p=project();if(!p&&['strategy','fabe','mh','pop','web','ecom'].includes(kind)){toast('这项演示需要产品与用途上下文。请先创建项目。');return}if(p&&!p.scopeConfirmed&&!['research','assets','notes'].includes(kind)){showModal('scope',p.id);return}const deps={fabe:['strategy'],mh:['fabe'],pop:['mh','assets'],web:['mh','assets'],ecom:['mh','assets']};if(kind==='fabe'&&!taskFor('strategy'))deps.fabe=[];const missing=(deps[kind]||[]).filter(k=>!byKind(k));if(missing.length){addMsg('assistant','还缺少 '+missing.map(k=>KIND[k].name).join('、')+' 作为输入。已有草稿即可，不要求上游先批准。',{action:'generate-'+missing[0]});render(true);return}const t=taskFor(kind);if(t&&t.assignee!==S.actor)return toast('请切换到 '+PEOPLE[t.assignee].name+' 再执行这项交付。',true);if(S.actor==='reviewer')return toast('审核角色不执行内容制作，请切换到负责人。',true);const pid=S.projectId,tid=S.threadId;return runWork(kind,async()=>{if(t&&t.assignee!==S.actor)throw new Error('执行期间责任发生变化，请重新发起');const refs=sourceRefs(deps[kind]||[],pid);if(kind==='strategy'){const pp=project(pid);for(const cr of pp?.contextRefs||[]){const ca=artifact(cr.id);if(ca)refs.push({id:ca.id,kind:ca.kind,revision:cr.revision,title:ca.title})}}const data=makeContent(kind);let a=byKind(kind,pid);if(a&&kind!=='notes'){const v=addRevision(a,data,'重新生成完整建议',refs);if(!v)throw new Error('当前角色不可写入')}else a=newArtifact(kind,data,pid,refs,tid);return{artifactIds:[a.id],text:kind==='research'?'已整理三项值得验证的观察。研究结果独立保存，不会自动建立项目；你可以展开详情，或之后引用到项目。':kind==='assets'?'找到 6 项示例素材，4 项适合演示用途，另 2 项因型号或授权问题排除。已选中的素材保存在集合中，可以继续调整。':'已形成'+KIND[kind].name+'草稿。核心内容已整理为卡片；展开后可以查看全文、依据和版本，也可以选中具体内容继续讨论。',action:nextAction(kind)};});}
function nextAction(kind){return({research:'create',strategy:'generate-fabe',fabe:'generate-mh',mh:'generate-assets',assets:'generate-pop',pop:'check',web:'deliverables'})[kind]||null}
function adopt(id,num){const a=artifact(id);if(!a||!canWrite(a))return;num=num||a.pending||a.active;const v=revision(a,num);if(!v)return;const was=a.active;a.active=num;a.accepted=num;if(a.pending===num)a.pending=null;const t=S.tasks.find(t=>t.id===a.taskId);if(t){t.status=t.maturity==='draft'?'done':'working';t.artifactId=a.id}log('已确认工作草稿',a.title+' v'+num+(was!==num?'，原版仍保留。':''),a.projectId);if(t?.maturity==='draft')toast('已确认草稿，这项交付已完成。不是正式批准。');else toast('已采用此版本。正式交付还需审核。');if(S.canvas)S.canvas.num=num;render();persist();}
async function modifySelected(instruction='请按当前反馈修改'){let a=artifact(S.contextSelection?.artifactId||S.canvas?.id);if(!a){a=byKind('pop')||byKind('mh')||byKind('strategy')}if(!a)return toast('先打开或选中一份成果再提出修改。');if(!canWrite(a))return;let n=S.contextSelection?.revision||S.canvas?.num||a.pending||a.active;let base=revision(a,n);const pid=a.projectId;return runWork('modify',async()=>{let d=clone(base.data);if(['pop','web','ecom'].includes(a.kind)){d.headline='Espacio para tu día a día.';d.reviewNote=instruction;}
else if(d.sections){let id=S.contextSelection?.section||'audience';let sec=d.sections.find(x=>x.id===id)||d.sections[0];sec.body='优先面向正在进行厨房升级或替换旧冰箱的用户，把空间整合与日常使用放在第一位；不再用“大家庭”作为泛化标签。该判断保持为待验证假设。';d.summary='围绕厨房升级这个明确时刻，组织空间、布局与取用便利的价值表达。';}
else if(a.kind==='mh'){d.claim='Espacio para tu día a día.';d.summary='Tu cocina, mejor organizada.';}else if(a.kind==='fabe'){d.points[0].benefit='让厨房升级后的食品与饮品收纳更有条理。';d.points[0].short='Organiza lo que importa.';}
const v=addRevision(a,d,'用户反馈：'+instruction,base.refs);if(!v)throw new Error('没有写入权限');S.canvas={id:a.id,num:v.num,tab:'content'};S.contextSelection=null;return{artifactIds:[a.id],text:'已基于 v'+n+' 形成 v'+v.num+' 新建议，原采用版本未改动。可以先比较完整内容，再决定采用；这不是一次正式审批。'};});}
function inspectContent(a,v){const data=JSON.stringify(v.data);const unsupported=/(省电\s*30%|保鲜\s*7\s*天|30%\s*(energy|ahorro)|7\s*días|销量第一)/i.test(data);const assetsOk=!(v.data.items||[]).some(id=>!assetItem(id)?.eligible);return{passed:!unsupported&&assetsOk,artifactId:a.id,revision:v.num,at:now(),findings:[{title:'产品事实与声明',ok:!unsupported,detail:unsupported?'包含没有适用依据的量化或排名声明，请删除后重试。':'未检测到样例禁用声明。依据仍限定于附件与演示数据。'},{title:'品牌与本地表达',ok:true,detail:'使用 es-MX 表达；主张与支撑层级清楚。该检查为模拟规则，不是法规认证。'},{title:'素材与使用范围',ok:assetsOk,detail:assetsOk?'素材引用保留版本与用途；内置图仅用于演示。':'有素材不具备本次使用条件。'}]};}
async function checkArtifact(id){let a=artifact(id||S.canvas?.id)||byKind('pop');if(!a)return toast('还没有可检查的成果。');let n=S.canvas?.id===a.id?S.canvas.num:a.pending||a.active;const v=revision(a,n);return runWork('check',async()=>{a.checks=a.checks||{};const check=inspectContent(a,v);a.checks[n]=check;log('已完成内容预检查',a.title+' v'+n+' · '+(check.passed?'可提交':'需修改'),a.projectId);return{artifactIds:[a.id],check,text:check.passed?'当前版本已通过本演示的事实、品牌与用途检查。AI 检查不会替你批准内容；提交时将固定这份成果的版本与来源。':'检查发现需要修改的内容，请打开结果定位问题。不会生成批准记录。',action:check.passed?'submit':null};});}
function submitArtifact(id,num){let a=artifact(id);if(!a||!canWrite(a))return;num=num||a.active;const v=revision(a,num);if(a.pending||a.active!==num||a.accepted!==num)return toast('请先明确采用要提交的完整版本。',true);if(!a.checks?.[num]?.passed)return toast('先对这一版本完成内容检查。',true);if(hasPendingSubmission(a))return toast('已经存在待审核提交，不会重复创建。');const t=S.tasks.find(t=>t.id===a.taskId);if(!t)return toast('这份成果还不是正式交付任务。');const s={id:uid('submission'),projectId:a.projectId,taskId:t.id,artifactId:a.id,title:a.title,revision:num,snapshot:clone(v),requirement:clone({text:t.requirement,maturity:t.maturity,ruleVersion:t.ruleVersion}),submitter:S.actor,reviewer:t.reviewer,status:'pending',submitted:now(),reviewComment:null};S.submissions.push(s);t.status='review';log('已提交固定成果版本',a.title+' v'+num+' → '+PEOPLE[s.reviewer].name,a.projectId);addMsg('assistant','已提交 '+a.title+' v'+num+'，审核对象和来源已固定。后续草稿不会改变本次提交。',{action:'review'});closeModal();render(true);persist();}
function reviewDecision(sid,decision,comment){const s=S.submissions.find(x=>x.id===sid);if(!s)return;if(S.actor!==s.reviewer)return toast('仅指定审核角色可以作出这个决定。',true);if(s.status!=='pending')return toast('这个提交已有决定，重复操作不产生新记录。');if(decision==='returned'&&!comment?.trim())return toast('请填写明确的修改意见。',true);s.status=decision;s.decided=now();s.reviewComment=comment||'批准本次固定成果版本。';const t=S.tasks.find(x=>x.id===s.taskId);if(t)t.status=decision==='approved'?'done':'working';log(decision==='approved'?'已批准固定成果':'已退回修改',s.title+' v'+s.revision+' · '+s.reviewComment,s.projectId);if(decision==='approved'){const d={id:uid('receipt'),submissionId:s.id,projectId:s.projectId,revision:s.revision,artifactId:s.artifactId,status:'pending',attempts:0,items:[{name:'成果内容',status:'pending'},{name:'预览与附件',status:'pending'}],created:now()};S.deliveries.push(d);ingest(d.id)}closeModal();render(true);persist();}
async function ingest(id,retry=false){const d=S.deliveries.find(x=>x.id===id);if(!d)return;if(d.status==='received'||d.status==='sending')return;d.status='sending';d.attempts++;d.items.filter(x=>x.status!=='received').forEach(x=>x.status='sending');persist();render();await new Promise(r=>setTimeout(r,window.__LILITH_QA_TIME_SCALE?30:1400));if(!S.deliveries.includes(d))return;if(!retry&&d.attempts===1){d.items[0].status='received';d.items[1].status='failed';d.status='partial';log('内容库接收部分完成','内容已接收，附件模拟超时；原批准与完成状态不变。',d.projectId)}else{d.items.forEach(x=>{x.status='received';x.receipt='DEMO-CL-'+d.id.slice(-7)+'-'+d.items.indexOf(x)});d.status='received';d.received=now();log('内容库接收完成','只重试失败项，没有重复创建批准或任务。',d.projectId)}persist();render();if(MODAL?.kind==='deliveries')renderModal();}
function requestTransfer(taskId){const t=S.tasks.find(x=>x.id===taskId);if(!t||S.actor!==t.assignee)return toast('只有当前负责人可以发起接手。',true);if(S.transfers.some(x=>x.taskId===taskId&&x.status==='pending'))return toast('已有待接手邀请。');let tr={id:uid('transfer'),taskId,projectId:t.projectId,from:S.actor,to:S.actor==='ana'?'lin':'ana',baseRevision:t.revision,status:'pending',created:now()};S.transfers.push(tr);log('已邀请协作者接手',t.name+' · 接受前负责人不变。');closeModal();render();persist();}
function acceptTransfer(id){const tr=S.transfers.find(x=>x.id===id),t=S.tasks.find(x=>x.id===tr?.taskId);if(!tr||!t)return;if(S.actor!==tr.to)return toast('只有指定接手人可以接受。',true);if(tr.status!=='pending')return toast('该邀请已经处理。');if(t.assignee!==tr.from||t.revision!==tr.baseRevision){tr.status='invalid';persist();render();return toast('责任已经变化，旧邀请已失效。',true)}tr.status='accepted';tr.accepted=now();t.assignee=tr.to;t.revision++;S.transfers.filter(x=>x.taskId===t.id&&x.id!==id&&x.status==='pending').forEach(x=>x.status='invalid');log('接手已完成',PEOPLE[tr.to].name+' 负责 '+t.name);render();persist();}
