const UTF8=new TextEncoder();
const CRC_TABLE=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xEDB88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xFFFFFFFF;for(const x of bytes)c=CRC_TABLE[(c^x)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0}
function concatBytes(parts){let total=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(total),i=0;for(const p of parts){out.set(p,i);i+=p.length}return out}
function zipStore(files){const parts=[],central=[];let offset=0;for(const [filename,value]of Object.entries(files)){const name=UTF8.encode(filename),data=typeof value==='string'?UTF8.encode(value):value,crc=crc32(data);const local=new Uint8Array(30+name.length),d=new DataView(local.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x0800,true);d.setUint32(14,crc,true);d.setUint32(18,data.length,true);d.setUint32(22,data.length,true);d.setUint16(26,name.length,true);local.set(name,30);parts.push(local,data);const c=new Uint8Array(46+name.length),v=new DataView(c.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x0800,true);v.setUint32(16,crc,true);v.setUint32(20,data.length,true);v.setUint32(24,data.length,true);v.setUint16(28,name.length,true);v.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=local.length+data.length}const csize=central.reduce((n,p)=>n+p.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,csize,true);v.setUint32(16,offset,true);return concatBytes([...parts,...central,end])}
function download(name,data,type='application/octet-stream'){let blob=data instanceof Blob?data:new Blob([data],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('已生成文件：'+name);return blob;}
function exportHTML(a,v,label='工作草稿'){return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(a.title)} v${v.num}</title><style>body{font-family:Arial,"PingFang SC","Microsoft YaHei",sans-serif;margin:40px auto;max-width:950px;padding:0 24px;color:#00284C;line-height:1.85}h1{font-size:29px;font-weight:400}aside{background:#E8F4FA;padding:18px;font-size:12px;margin:20px 0}pre{white-space:pre-wrap;word-break:break-word;font:inherit;font-size:13px}.poster{display:block;max-width:490px;width:100%;margin:auto}button{display:none}.website-preview{border:1px solid #D6E0E7}.website-nav{padding:12px}.web-hero{display:flex;padding:24px;background:#F1F5F7}.web-hero>div{flex:1}.fridge{width:35%;height:230px}.web-points{padding:24px}.web-points section{margin:20px 0}</style><h1>${E(a.title)}</h1><aside>${E(label)} · v${v.num}<br>OFFLINE DEMO · 固定版本导出。产品图为概念示意，研究、模型及企业工具为模拟。不作为正式商业物料或印刷母版。</aside>${a.kind==='pop'?posterSvg(v.data):['web','ecom'].includes(a.kind)?webHTML(a,v):`<pre>${E(documentText(a,v))}</pre>`}<h2>来源与版本</h2><pre>${E(JSON.stringify(v.refs,null,2))}</pre></html>`;}
function versionFiles(a,v,label){let stem=a.kind+'_v'+v.num;const files={};files[stem+'.html']=exportHTML(a,v,label);files[stem+'.md']='> '+label+' · OFFLINE DEMO · v'+v.num+'\n\n'+documentText(a,v);files[stem+'.json']=JSON.stringify({artifactId:a.id,kind:a.kind,title:a.title,status:label,revision:clone(v)},null,2);if(a.kind==='pop')files[stem+'.svg']=posterSvg(v.data);if(a.kind==='assets'){for(const id of v.data.items){const item=assetItem(id);if(!item)continue;if(item.dataURL){const match=item.dataURL.match(/^data:image\/(png|jpeg|webp);base64,(.+)$/);if(match)files['selected-assets/'+id+'.'+(match[1]==='jpeg'?'jpg':match[1])]=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));}else files['selected-assets/'+id+'.svg']=['warm','cool'].includes(item.view)?kitchen(item.view):fridge(item.view,'fridge',true);}}return files;}
function exportOne(id,num){const a=artifact(id),v=revision(a,num);if(!v)return;download('Lilith_'+a.kind+'_v'+v.num+'.zip',zipStore(versionFiles(a,v,versionLabel(a,num)[0])),'application/zip')}
function exportApproved(sid){const s=S.submissions.find(x=>x.id===sid&&x.status==='approved');if(!s)return toast('不存在有效的已批准提交。',true);const a=artifact(s.artifactId);const files=versionFiles(a,s.snapshot,'已批准固定快照');files['approval.json']=JSON.stringify(s,null,2);files['receipt.json']=JSON.stringify(S.deliveries.filter(d=>d.submissionId===s.id),null,2);download('Lilith_'+a.kind+'_approved_v'+s.revision+'.zip',zipStore(files),'application/zip')}
function exportProject(pid=S.projectId){const p=project(pid);if(!p)return toast('请先进入一个项目。');let files={},entries=[];for(const t of S.tasks.filter(x=>x.projectId===p.id&&x.status==='done')){const a=artifact(t.artifactId);if(!a)continue;const sub=t.maturity==='approved'?S.submissions.findLast(s=>s.taskId===t.id&&s.status==='approved'):null;const v=sub?.snapshot||revision(a,a.accepted);if(!v)continue;const label=sub?'已批准固定快照':'已确认工作草稿';const fs=versionFiles(a,v,label);Object.entries(fs).forEach(([n,b])=>files[t.kind+'/'+t.id+'/'+n]=b);entries.push({taskId:t.id,artifactId:a.id,title:a.title,revision:v.num,status:label,submissionId:sub?.id||null});}
if(!entries.length)return toast('还没有已完成交付，可以先单独导出一份草稿。');files['manifest.json']=JSON.stringify({appVersion:APP_VERSION,project:clone(p),entries,omitted:S.tasks.filter(t=>t.projectId===p.id&&t.status!=='done').map(t=>({id:t.id,name:t.name,status:t.status})),scope:'只导出已完成交付所采用的草稿或批准快照；不混入后续未采用候选。',simulation:true},null,2);files['sources.json']=JSON.stringify(SOURCES,null,2);files['approvals.json']=JSON.stringify(S.submissions.filter(s=>s.projectId===p.id),null,2);files['receipts.json']=JSON.stringify(S.deliveries.filter(s=>s.projectId===p.id),null,2);files['activity.json']=JSON.stringify(S.activity.filter(s=>s.projectId===p.id),null,2);files['README.txt']='Lilith Agent-first 离线 Demo 交付包。\n草稿与正式批准严格分开标识。所有企业连接为模拟。\n页面可浏览，POP SVG 可预览；不是商用或印刷文件。\n真实运行与仓库集成需要 Codex 核验。';download('Lilith_SpaceMaster_交付包.zip',zipStore(files),'application/zip');}
async function exportPng(id,num){const a=artifact(id),v=revision(a,num);if(a?.kind!=='pop')return;const svg=posterSvg(v.data),im=new Image();im.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await new Promise((res,rej)=>{im.onload=res;im.onerror=rej});const c=document.createElement('canvas');c.width=1200;c.height=1800;const ctx=c.getContext('2d');ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);const b=await new Promise(res=>c.toBlob(res,'image/png'));download('Lilith_POP_v'+num+'_screen.png',b,'image/png');}
