/* State/contract tests. Browser evidence is separately recorded, never inferred here. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
function harness(saved=null){
  const build=fs.readFileSync(path.join(root,'src/demo-spacemaster-v6/build.mjs'),'utf8');
  const base=JSON.parse(build.match(/const parts=(\[[^\n]+\]);/)[1].replaceAll("'",'"')).map(x=>'base/'+x+'.js');
  const more=JSON.parse(build.match(/\['merged\.js'[^\n]+?'release-policy\.js'\]/)[0].replaceAll("'",'"'));
  const copy=vm.runInNewContext(fs.readFileSync(path.join(root,'src/demo-spacemaster-v6/product-copy.mjs'),'utf8').replace('export function productCopy','function productCopy')+';productCopy');
  const writes=[],reads=[],timers=new Map(),dock={innerHTML:'',querySelector:()=>null,querySelectorAll:()=>[],appendChild(){},setAttribute(){}};
  const document={addEventListener(){},removeEventListener(){},querySelector:s=>s==='#modal-root'?dock:null,querySelectorAll:()=>[],getElementById:()=>null,body:{appendChild(){}},documentElement:{dataset:{}},fonts:{ready:Promise.resolve()},activeElement:null};
  const context={window:{MARKETING_DESKTOP:true,addEventListener(){}},document,localStorage:{getItem:k=>{reads.push(k);return saved;},setItem:(k,v)=>writes.push([k,v])},MERGED_ASSETS:{images:{},logo:'',actionIcons:{},scenarios:{},demoImages:JSON.parse(fs.readFileSync(path.join(root,'public/demo-spacemaster-v6/manifest.json'),'utf8'))},console,URL,FormData,TextEncoder,TextDecoder,Uint8Array,atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s).toString('base64'),setTimeout:fn=>{const id=timers.size+1;timers.set(id,fn);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame:fn=>fn(),innerWidth:1440,HTMLElement:class{},ResizeObserver:class{observe(){}disconnect(){}},MutationObserver:class{observe(){}disconnect(){}}};
  vm.createContext(context);const run=code=>vm.runInContext(code,context);
  for(const name of [...base,...more])vm.runInContext(copy(fs.readFileSync(path.join(root,'src/demo-spacemaster-v6',name),'utf8')),context,{filename:name});
  for(const name of ['model.js','scenes.js','contracts.js','workspace.js'])vm.runInContext(fs.readFileSync(path.join(root,'src/marketing-desktop',name),'utf8'),context,{filename:name});
  run("render=()=>{};renderModal=()=>{};mountDock=()=>{};scheduleText=()=>{};toast=()=>{};MD.boot();");
  return {run,writes,reads,state:run('S'),timers,json:code=>JSON.parse(JSON.stringify(run(code)))};
}
function brand(h){h.run("MD.meta().scene='brand';MD.meta().goal=MD.scenes.brand.goal;MD.loadFixtures();var plan=MD.newPlan();");}
test('independent storage is used from initial load, with no seeded projects',()=>{const h=harness();h.run('persist()');assert.equal(h.state.projects.length,0);assert.deepEqual(h.reads,['mokina-marketing-desktop-prototype']);assert.ok(h.writes.every(([key])=>key==='mokina-marketing-desktop-prototype'));});
test('saving edited plan preserves item identity and creates no result',()=>{const h=harness();brand(h);const id=h.run('plan.items[0].id');h.run("MD.savePlan(plan,{goal:'新目标',exclusions:'不要图片'});");assert.equal(h.run('plan.items[0].id'),id);assert.equal(h.run('plan.goal'),'新目标');assert.equal(h.state.artifacts.length,0);assert.equal(h.run('plan.history.length'),1);});
test('async result stays with A while B has its own draft, repeated return ignored',()=>{const h=harness();brand(h);const tid=h.state.threadId;h.run("var run=MD.execute(plan.id);newChat();DRAFTS[S.threadId]='B 的草稿';MD.finish(run.id);MD.finish(run.id);");assert.equal(h.state.artifacts.length,1);assert.equal(h.state.artifacts[0].threadId,tid);assert.notEqual(h.state.threadId,tid);assert.equal(h.run('DRAFTS[S.threadId]'),'B 的草稿');assert.equal(h.state.canvas,null);});
test('cancelled late completion never creates result',()=>{const h=harness();brand(h);h.run('var r=MD.execute(plan.id);MD.cancel(r.id);MD.finish(r.id)');assert.equal(h.state.artifacts.length,0);assert.equal(h.run('r.status'),'cancelled');});
test('run fixes input variant despite subsequent source replacement',()=>{const h=harness();brand(h);h.run("var r=MD.execute(plan.id);MD.loadFixtures('changed');MD.finish(r.id)");assert.match(h.state.artifacts[0].versions[0].data.summary,/年轻租住/);h.run('var r2=MD.execute(plan.id,false,{repeat:true});MD.finish(r2.id)');assert.match(h.state.artifacts[1].versions[0].data.summary,/有孩子家庭/);assert.notEqual(h.state.artifacts[0].versions[0].contextSnapshotId,h.state.artifacts[1].versions[0].contextSnapshotId);});
test('custom input cannot be relabelled as scenario-generated',()=>{const h=harness();brand(h);h.run("S.uploads.push({id:'custom',name:'访谈.txt',text:'自有资料',threadId:S.threadId});MD.meta().selected=[{id:'custom',type:'upload',revision:1}];");assert.throws(()=>h.run('MD.execute(plan.id)'),/不能声称据此生成/);assert.equal(h.state.artifacts.length,0);});
test('brand why only explains, alternate is a cancellable separate artifact',async()=>{const h=harness();brand(h);h.run('var r=MD.execute(plan.id);MD.finish(r.id)');await h.run("sendPrompt('为何不同时覆盖两个受众？')");assert.equal(h.state.artifacts.length,1);assert.equal(h.state.artifacts[0].versions.length,1);await h.run("sendPrompt('保留方向，再补一个对照方案')");assert.equal(h.state.artifacts.length,1);assert.equal(h.state.md.runs.at(-1).status,'running');h.run('MD.finish(S.md.runs.at(-1).id)');assert.equal(h.state.artifacts.length,2);assert.notEqual(h.state.artifacts[0].id,h.state.artifacts[1].id);});

test('all alternative aliases share negation and create neither artifacts nor plan items',async()=>{
  const h=harness();brand(h);h.run('MD.finish(MD.execute(plan.id).id)');
  for(const mode of ['collaborate','plan']){h.run('S.workModes[S.threadId]='+JSON.stringify(mode));for(const prompt of ['先不做第二个方案，保留当前这一份就好。','不要另一份方案','暂不制作对照方案','先不制作对照方案']){await h.run('sendPrompt('+JSON.stringify(prompt)+')');assert.equal(h.state.artifacts.length,1);assert.equal(h.state.plans[0].items.length,1);assert.equal(h.state.md.runs.length,1);}}
});
test('negative image clause does not veto a positive text action; ambiguity never runs',()=>{
  const h=harness();assert.equal(h.run("MD.parseIntent('不要图片，只制作五条文字').polarity"),'positive');assert.equal(h.run("MD.parseIntent('不要图片，只制作五条文字').action"),'start');
  for(const text of ['不是不做第二个方案','先生成一份，再生成另一份方案'])assert.equal(h.run('MD.parseIntent('+JSON.stringify(text)+').polarity'),'clarify');
});
test('brand exclusion changes actual touchpoints; unknown scope creates no run or snapshot',()=>{
  const h=harness();brand(h);h.run("MD.savePlan(plan,{exclusions:'不要小红书，不要文字答疑，只做微信公众号。'});MD.finish(MD.execute(plan.id).id)");
  const data=h.state.artifacts[0].versions[0].data;assert.deepEqual(JSON.parse(JSON.stringify(data.config.touchpoints)),['wechat']);assert.doesNotMatch(data.sections.find(x=>x.id==='touchpoints').body,/小红书|答疑/);
  h.run("newChat();MD.meta().scene='brand';MD.meta().goal=MD.scenes.brand.goal;MD.loadFixtures();var bad=MD.newPlan();bad.exclusions='只做抖音';");const snapshots=h.state.md.snapshots.length;assert.throws(()=>h.run('MD.execute(bad.id)'),/尚未覆盖/);assert.equal(h.state.md.snapshots.length,snapshots);assert.equal(h.state.md.runs.length,1);
});
test('social parameters control actual count channel and Gregorian schedule',()=>{
  const h=harness();h.run("MD.meta().scene='social';MD.meta().goal=MD.scenes.social.goal;MD.loadFixtures();var p=MD.newPlan();p.items[0].config={count:3,channel:'wechat',startDate:'2026-12-31'};p.items[0].configExplicit=true;");
  assert.throws(()=>h.run('MD.execute(p.id)'),/冲突/);
  h.run("p.goal=p.goal.replace('五条','三条');var run=MD.execute(p.id);var ids=run.prepared[0].posts.map(p=>p.id);MD.finish(run.id)");
  const posts=h.json('S.artifacts[0].versions[0].data.posts');assert.equal(posts.length,3);assert.deepEqual(posts.map(p=>p.date),['2026-12-31','2027-01-01','2027-01-02']);assert.ok(posts.every(p=>p.channel==='微信公众号'));assert.deepEqual(posts.map(p=>p.id),h.json('ids'));
});
test('structured/text conflicts and unsupported plan fields block generation',()=>{
  const h=harness();brand(h);h.run("plan.items[0].config={touchpoints:['xiaohongshu']};plan.items[0].configExplicit=true;plan.exclusions='只做微信公众号'");assert.throws(()=>h.run('MD.execute(plan.id)'),/冲突/);
  h.run("plan.exclusions='不发布';plan.items[0].output='声称市场份额提升百分之十'");assert.throws(()=>h.run('MD.execute(plan.id)'),/未覆盖/);assert.equal(h.state.artifacts.length,0);
});
test('scope validation rejects contradictory fields and another scene goal',()=>{
  const h=harness();h.run("MD.meta().scene='social';MD.meta().goal=MD.scenes.social.goal;var p=MD.newPlan();p.items[0].output='三条文字'");
  assert.ok(h.run('MD.planIssues(p).some(s=>s.includes("不同条数"))'));
  assert.ok(h.run("MD.scopeInput(MD.scenes.analytics.goal,'marketing-memo').errors.length>0"));
  assert.ok(h.run("MD.scopeInput('三条文字，五条文字','social-calendar').errors.length>0"));
  assert.ok(h.run("MD.scopeInput('不要五条文字','social-calendar').errors.length>0"));
  assert.deepEqual(h.json("MD.scopeInput('排除小红书与答疑，只选公众号','marketing-memo').excluded"),['xiaohongshu','discussion']);
});
test('partial source changes revision and body together without mutating historical snapshot',()=>{
  const h=harness();brand(h);h.run("MD.finish(MD.execute(plan.id).id);var a=S.artifacts[0],old=clone(a.versions[0].data);var next=clone(old);next.sections[0].body='新版家庭方向';MD.revise(a.id,1,next,'测试');newChat();MD.meta().selected=[{type:'artifact',id:a.id,revision:1,selection:['audience'],summary:'旧缓存'}];var s1=MD.snapshot(S.threadId,'v1');MD.meta().selected[0].revision=2;var s2=MD.snapshot(S.threadId,'v2');var doc=MD.addResult(S.threadId,{title:'引用测试',sections:[]},'marketing-document',s2,'user-document');");
  assert.match(h.run('s2.selected[0].text'),/新版家庭方向/);assert.doesNotMatch(h.run('s2.selected[0].text'),/旧缓存/);assert.match(h.run('s1.selected[0].text'),/年轻租住/);assert.match(h.run('documentText(doc,doc.versions[0])'),/新版家庭方向/);
  h.run("a.versions[1].data.sections=[]");assert.throws(()=>h.run("MD.snapshot(S.threadId,'missing')"),/缺少所选段落/);
});
test('historical mismatch is reported, not rewritten, and revoked source cannot resolve',()=>{
  const h=harness();brand(h);h.run("MD.finish(MD.execute(plan.id).id);var a=S.artifacts[0];var s=MD.snapshot(S.threadId,'history');s.selected=[{type:'artifact',id:a.id,revision:1,selection:['audience'],text:'旧错误正文',data:{sections:[{id:'audience',body:'新正文'}]}}];a.versions[0].contextSnapshotId=s.id;var before=JSON.stringify(s)");assert.match(h.run('refsHTML(a,a.versions[0])'),/历史引用不一致/);assert.equal(h.run('JSON.stringify(s)'),h.run('before'));h.run('a.revoked=true');assert.throws(()=>h.run("MD.resolve({type:'artifact',id:a.id,revision:1,selection:['audience']})"),/撤回/);
});
test('explicit start in plan mode executes saved single item, save and explanation do not',async()=>{
  const h=harness();brand(h);h.run("MD.savePlan(plan,{});S.workModes[S.threadId]='plan'");assert.equal(h.state.md.runs.length,0);await h.run("sendPrompt('开始制作')");assert.equal(h.state.md.runs.length,1);assert.equal(h.state.md.runs[0].status,'running');h.run('MD.finish(S.md.runs[0].id)');await h.run("sendPrompt('为什么选择这个受众？')");assert.equal(h.state.md.runs.length,1);assert.equal(h.state.artifacts[0].versions.length,1);
});
test('completed work does not rerun without explicit repeat; all runs unfinished only',()=>{
  const h=harness();brand(h);h.run("MD.finish(MD.execute(plan.id).id);plan.items.push({id:'next',title:'普通文档',kind:'marketing-document',status:'pending'});var r2=MD.execute(plan.id,true);MD.finish(r2.id)");assert.equal(h.state.artifacts.length,2);assert.throws(()=>h.run('MD.execute(plan.id,true)'),/已完成/);assert.equal(h.state.md.runs.length,2);
});
test('alternate cancellation and late callback preserve original artifact',async()=>{
  const h=harness();brand(h);h.run('MD.finish(MD.execute(plan.id).id)');await h.run("sendPrompt('再做一份对照方案')");h.run('var r=S.md.runs.at(-1);MD.cancel(r.id);MD.finish(r.id)');assert.equal(h.state.artifacts.length,1);assert.equal(h.state.md.runs.at(-1).status,'cancelled');
});
test('followup requires selected supporting analysis and never works from an empty selection',()=>{
  const h=harness();h.run("MD.meta().goal=MD.scenes.analytics.goal;var s=MD.snapshot(S.threadId,'analysis'),a=MD.addResult(S.threadId,MD.analysisData(MD.calculate(MD.fixtures.analytics[0].text)),'operations-analysis',s,'local-computation');newChat();var m=MD.meta();m.scene='social';m.followup=true;m.goal='依据所选结论，制定下周三条实用内容计划；具体产品事实后续补充。';var p=MD.newPlan();");assert.throws(()=>h.run('MD.execute(p.id)'),/请选用/);
  h.run("m.selected=[{type:'artifact',id:a.id,revision:1,selection:['limits']}]");assert.throws(()=>h.run('MD.execute(p.id)'),/未覆盖此接续/);
  h.run("m.selected[0].selection=['mix'];MD.finish(MD.execute(p.id).id)");assert.equal(h.state.artifacts.at(-1).versions[0].data.posts.length,3);
});
test('third post candidate preserves four other posts, original and adoption',()=>{const h=harness();h.run("MD.meta().scene='social';MD.meta().goal=MD.scenes.social.goal;MD.loadFixtures();var p=MD.newPlan(),r=MD.execute(p.id);MD.finish(r.id);var a=S.artifacts[0];adopt(a.id,1);var d=clone(a.versions[0].data);d.posts[2].body='只修改第三条';var v=MD.revise(a.id,1,d,'用户编辑',d.posts[2].id)");const a=h.state.artifacts[0];assert.equal(a.accepted,1);assert.equal(a.active,1);assert.equal(a.pending,2);for(const i of [0,1,3,4])assert.deepEqual(a.versions[0].data.posts[i],a.versions[1].data.posts[i]);assert.notEqual(a.versions[0].data.posts[2].body,a.versions[1].data.posts[2].body);});
test('stale base becomes conflict candidate instead of overwriting',()=>{const h=harness();brand(h);h.run("var r=MD.execute(plan.id);MD.finish(r.id);var a=S.artifacts[0];MD.revise(a.id,1,a.versions[0].data,'第一次');MD.revise(a.id,1,a.versions[0].data,'迟到修订')");assert.equal(h.state.artifacts[0].versions[2].conflict,true);assert.equal(h.state.artifacts[0].active,1);});
test('exact Spec CSV totals, groups and decomposition',()=>{const h=harness();const r=h.json('MD.calculate(MD.fixtures.analytics[0].text)');assert.equal(r.totals[0].impressions,40000);assert.equal(r.totals[1].interactions,1550);assert.equal(r.totals[0].rate,.0525);assert.equal(r.totals[1].rate,.03875);assert.equal(r.groups[0].values[1].rate,.065);assert.ok(Math.abs(r.delta+.01375)<1e-12);assert.ok(Math.abs(r.composition+.015)<1e-12);assert.ok(Math.abs(r.within-.00125)<1e-12);});
test('CSV rejects invalid inputs and does not guess chronological string order',()=>{const h=harness();for(const [s,pattern] of [['period,content_type,impressions\na,b,1',/interactions/],['period,content_type,impressions,interactions\na,b,x,1',/第 2 行.*impressions/],['period,content_type,impressions,interactions\na,b,1',/实际 3/],['period,content_type,impressions,interactions\n"a,b,1,2',/引号未闭合/]]){h.run('var bad='+JSON.stringify(s));assert.throws(()=>h.run('MD.parseCSV(bad)'),pattern);}assert.throws(()=>h.run("MD.calculate(MD.fixtures.analytics[0].text,'x','y')"),/明确选择/);assert.throws(()=>h.run("MD.calculate(MD.fixtures.analytics[0].text.replaceAll('30000','0').replaceAll('10000','0'))"),/曝光合计为零/);});
test('quoted CSV and BOM are parsed without losing comma in group name',()=>{const h=harness();h.run('var csv='+JSON.stringify('\uFEFFperiod,content_type,impressions,interactions\r\nprevious,"tips, daily",100,5\r\ncurrent,"tips, daily",100,6'));assert.equal(h.run('MD.calculate(csv).groups[0].group'),'tips, daily');});
test('selected conclusion only, fixed source version, no complete upstream text',()=>{const h=harness();h.run("MD.meta().goal='分析';var s=MD.snapshot(S.threadId,'test'),a=MD.addResult(S.threadId,MD.analysisData(MD.calculate(MD.fixtures.analytics[0].text)),'operations-analysis',s,'local-computation');newChat();MD.meta().selected=[{type:'artifact',id:a.id,revision:1,selection:['mix'],summary:a.versions[0].data.sections[1].body}];var snap=MD.snapshot(S.threadId,'接续')");const selected=h.json('snap.selected[0]');assert.equal(selected.data.sections.length,1);assert.equal(selected.data.sections[0].id,'mix');assert.doesNotMatch(selected.text,/实验一|销量或广告收益/);});
test('refresh restores drafts and marks interrupted simulation',()=>{const h=harness();brand(h);h.run("DRAFTS[S.threadId]='草稿仍在';MD.execute(plan.id);persist()");const saved=h.writes.at(-1)[1],restored=harness(saved);assert.equal(restored.run('DRAFTS[S.threadId]'),'草稿仍在');assert.equal(restored.state.md.runs[0].status,'interrupted');assert.equal(restored.state.artifacts.length,0);});
test('unknown artifact survives full content/export and restore',()=>{const h=harness();h.run("var a=newArtifact('unknown-format',{title:'未知文件',value:'保留内容'},null,[],S.threadId);persist()");assert.match(h.run('contentHTML(a,a.versions[0])'),/保留内容/);assert.match(h.run('documentText(a,a.versions[0])'),/保留内容/);const restored=harness(h.writes.at(-1)[1]);assert.equal(restored.state.artifacts[0].kind,'unknown-format');});
test('legacy import is idempotent, ambiguous owners stay historical',()=>{const h=harness();brand(h);h.run("var r=MD.execute(plan.id);MD.finish(r.id);var backup=clone(S);delete backup.artifacts[0].threadId;backup.threads.push({id:'other',title:'其他',messages:[{artifactIds:[backup.artifacts[0].id]}]});backup.artifacts[0].id='history';for(const t of backup.threads)t.messages=[];MD.importBackup(backup);MD.importBackup(backup)");assert.equal(h.state.artifacts.filter(a=>a.id==='history').length,1);assert.equal(h.state.artifacts.find(a=>a.id==='history').threadId,null);});

test('fixed snapshot includes plan exclusion and original actor',()=>{const h=harness();brand(h);h.run("MD.savePlan(plan,{exclusions:'不发布，不新增触点'});var r=MD.execute(plan.id);S.actor='ana';MD.finish(r.id)");assert.equal(h.state.artifacts[0].versions[0].author,'lin');assert.equal(h.state.md.snapshots[0].plan.exclusions,'不发布，不新增触点');});
test('source version changes only next snapshot, revoked local source blocked',()=>{const h=harness();brand(h);h.run("var r=MD.execute(plan.id);MD.finish(r.id);var a=S.artifacts[0];MD.revise(a.id,1,{title:'新版',sections:[{id:'audience',body:'新版本正文'}]},'修改');MD.meta().selected=[{type:'artifact',id:a.id,revision:1}];var s1=MD.snapshot(S.threadId,'引用');MD.meta().selected[0].revision=2;var s2=MD.snapshot(S.threadId,'引用');");assert.equal(h.run('s1.selected[0].revision'),1);assert.equal(h.run('s2.selected[0].revision'),2);h.run('a.revoked=true');assert.throws(()=>h.run("MD.snapshot(S.threadId,'新引用')"),/撤回/);});
test('plan mode alternate adds delivery without generating; negative request preserves result',async()=>{const h=harness();brand(h);h.run('var r=MD.execute(plan.id);MD.finish(r.id);S.workModes[S.threadId]="plan"');await h.run("sendPrompt('再补一个对照方案')");assert.equal(h.state.artifacts.length,1);assert.equal(h.run('plan.items.length'),2);await h.run("sendPrompt('不要另做对照方案')");assert.equal(h.state.artifacts.length,1);assert.equal(h.run('plan.items.length'),2);});
test('workflow continuation keeps creation work on save after navigation',()=>{const h=harness();brand(h);h.run("var r=MD.execute(plan.id);MD.finish(r.id);var a=S.artifacts[0];var job=window.V62Workflows.continueFrom({sourceId:a.id,revision:1,mode:'extension',market:'中国',language:'中文',channel:'文字',change:'只改表达',body:'待编辑草稿'});var owner=S.threadId;newChat();var saved=window.V62Workflows.saveContinuation(job.id,{body:'切换后保存'})");assert.equal(h.run('saved.threadId'),h.run('owner'));assert.notEqual(h.run('saved.threadId'),h.state.threadId);});
test('backup primitive arrays are not collapsed under missing id',()=>{const h=harness();h.run("var b=clone(S);b.selectedAssets=['a','b'];MD.importBackup(b);MD.importBackup(b)");assert.deepEqual(h.json('S.selectedAssets').slice(-2),['a','b']);assert.equal(h.json('S.selectedAssets').filter(x=>x==='a').length,1);});
