const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const file='美的 GTM Demo v3.html';
const raw=fs.readFileSync(file,'utf8').match(/<script>([\s\S]*)<\/script>/)[1];
const script=raw.replace(/document.addEventListener\('click'[\s\S]*?(?=const LEGACY_COPY=)/,'').split('\nrender();\nsetInterval')[0];
function app(search='',saved=null){const box={console,URLSearchParams,TextEncoder,TextDecoder,URL,Blob,Uint8Array,DataView,Date,Math,JSON,setTimeout,clearTimeout,performance,location:{search},localStorage:{getItem:()=>saved,setItem(){}},document:{querySelector(){return null},querySelectorAll(){return []}},window:{}};vm.createContext(box);vm.runInContext(script,box);return {run:s=>vm.runInContext(s,box),box};}
function visible(html){return html.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ')}
const forbidden=/Demo|演示|模拟|离线|本原型|OFFLINE|undefined|history-(?:pop|sub|audit|cl)|DEMO-(?:CL|CANVA|REQ)|templateVersion|Selling Point Naming|Description (?:Short|Long)/i;
function clean(markup,label){const text=visible(markup);assert.doesNotMatch(text,forbidden,label+': '+text.match(forbidden)?.[0]);}

test('default navigation mounts no debug controls and direct dispatch is ignored',()=>{const a=app();const h=a.run('shell()');clean(h,'shell');for(const action of ['tour','about','reset','preferences','autostart','backup','restore-backup']){assert.ok(!h.includes('data-action="'+action+'"'));a.run(`handleAction('${action}')`);assert.equal(a.run('S.modal'),null);}assert.ok(!h.includes('id="roleSelect"'));assert.equal(a.run('playerHtml()'),'');});
test('developer controls remain opt-in and mobile navigation is business navigation',()=>{const a=app('?dev=1');assert.match(a.run('shell()'),/开发设置/);assert.match(a.run('shell()'),/id="roleSelect"/);const b=app();clean(b.run("modalContent({type:'navigation'}).body"),'mobile navigation');assert.match(b.run("modalContent({type:'navigation'}).body"),/成果中心/);assert.doesNotMatch(b.run("modalContent({type:'navigation'}).body"),/导览|自动播放/);});
test('top-level pages and all four creation steps have product copy',()=>{const a=app();for(const view of ['home','projects','library','templates','markets','project','plan','sources']){a.run(`S.view='${view}';S.pid='FX-REVISION'`);clean(a.run('shell()'),view);}a.run("render=()=>{};nav=()=>{};openWizard();");for(let step=0;step<4;step++){a.run(`S.wizard.step=${step}`);clean(a.run('wizardPage()'),'wizard '+step);}assert.doesNotMatch(a.run('wizardPage()'),/wizFacts/);});
test('workspaces, candidate content, audit and editable dialogs do not expose internal annotations',()=>{const a=app();for(const type of ['strategy','fabe','mh','pop']){a.run(`S.pid='FX-REVISION';const t_${type}=newTask('${type}',S.pid);S.tasks[t_${type}.id]=t_${type};S.tid=t_${type}.id;t_${type}.status='working';const v_${type}={id:t_${type}.id+'-v1',num:1,status:'draft',data:taskDefaults('${type}'),refs:[],created:now(),author:'lin'};t_${type}.versions=[v_${type}];t_${type}.current=v_${type}.id;t_${type}.popStep=4;`);clean(a.run('workspace()'),type);a.run('auditOne(task(),current())');clean(a.run('auditPage()'),type+' audit');for(const modal of ['versions','metadata','canva','skill','template-item','quick']){if(modal==='canva'&&type!=='pop')continue;const arg=modal==='skill'?'GTM':modal==='template-item'?'Hero|strategy':modal==='quick'?'asset':'';clean(a.run(`JSON.stringify(modalContent({type:'${modal}',arg:'${arg}'}))`),type+' '+modal);}}});
test('POP steps use real product images and preserve missing-scene and print limitations',()=>{const a=app();a.run("S.pid='FX-REVISION';S.tid='history-pop';task().status='working';");for(let i=0;i<5;i++){a.run('task().popStep='+i);clean(a.run('popWork(task(),current())'),'POP step '+i);}assert.match(a.run("fridge('front')"),/data:image\/webp;base64/);assert.match(a.run('posterSvg(current().data,true)'),/data:image\/webp;base64/);assert.match(a.run("kitchen('warm')"),/待补场景图片/);assert.doesNotMatch(a.run('posterSvg(current().data,true)'),/Demo|DEMO|Imagen ilustrativa/);});
test('old default copy migrates idempotently without changing user edits or object references',()=>{const old=app();old.run("S.projects[1].name='SpaceMaster · 已批准 POP 样例';S.tasks['history-pop'].versions[0].data.footer='MDRS761MYM45A · Demo de comunicación. Imagen ilustrativa.';S.tasks['history-pop'].messages=[{role:'user',text:'Demo 演示是我输入的需求'},{role:'ai',text:'自定义文字不应被替换'}];S.tasks['history-pop'].versions[0].data.title='客户自己修改的标题';delete S.productCopyRevision;");const before=old.run('JSON.stringify(S)');const migrated=app('',before);assert.equal(migrated.run("S.tasks['history-pop'].versions[0].id"),'history-pop-v1');assert.equal(migrated.run("S.tasks['history-pop'].versions[0].data.footer"),'MDRS761MYM45A');assert.equal(migrated.run("S.tasks['history-pop'].versions[0].data.title"),'客户自己修改的标题');assert.equal(migrated.run("S.tasks['history-pop'].messages[0].text"),'Demo 演示是我输入的需求');assert.equal(migrated.run("S.projects[1].name"),'SpaceMaster · 墨西哥门店 POP');const once=migrated.run('JSON.stringify(S)');migrated.run('productModeState(S)');assert.equal(migrated.run('JSON.stringify(S)'),once);});
test('unconnected CL does not claim successful external delivery or fabricate receipts',()=>{const a=app();assert.equal(a.run('S.deliveries[0].status'),'not_connected');a.run("S.pid='FX-REVISION';S.tid='history-pop';const newSub={id:'new-sub',revId:current().id,snapshot:clone(current()),auditId:'audit-test'};createDelivery(task(),newSub);deliveryTick();");assert.equal(a.run('S.deliveries.at(-1).status'),'not_connected');assert.equal(a.run('S.deliveries.at(-1).items[0].clId'),null);clean(a.run('detailPage()'),'unconnected delivery');assert.match(a.run('detailPage()'),/未入库/);});
test('newly generated strategy, FABE, MH and POP messages and reports remain clean',()=>{const a=app();a.run('render=()=>{};toast=()=>{};');for(const type of ['strategy','fabe','mh','pop']){a.run(`S.pid='FX-REVISION';const generated_${type}=newTask('${type}',S.pid);S.tasks[generated_${type}.id]=generated_${type};S.tid=generated_${type}.id;task().status='working';task().popStep=3;startRun('generate',{data:taskDefaults('${type}')});finishRun(S.run);S.run=null;`);clean(a.run('workspace()'),type+' generated');clean(a.run('agentPanel(task())'),type+' agent');}});
test('business exports contain no raw schema files and use readable references',async()=>{const a=app();for(const id of ['global-strategy','global-fabe','global-mh','history-pop']){a.run(`S.tid='${id}';S.pid=task().projectId;`);clean(a.run('exportHtml(task(),current())'),id+' HTML');if(id!=='history-pop'){const files=await a.run('versionFiles(task(),current())');assert.ok(Object.keys(files).every(n=>!n.endsWith('.json')));for(const [name,body]of Object.entries(files))clean(body,name);}}});
