const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'Lilith Workspace.html'),'utf8');
const seed=JSON.parse(html.match(/window\.LILITH_SEED=(.*?);<\/script>/s)[1]);
function harness(saved){let disk=saved;const ctx={window:{LILITH_SEED:seed},localStorage:{getItem:()=>disk,setItem:(_,v)=>{disk=v}},console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'src/workspace/model.js'),'utf8'),ctx);return {api:ctx.window.Lilith,get saved(){return disk}}}
function setup(){const h=harness(),a=h.api,p=a.createProject('SpaceMaster 墨西哥上市');a.confirmPlan(p.id,p.plan);return {h,a,p}}
test('clear intent creates a context space before any delivery commitments',()=>{const {api:a}=harness();const p=a.createProject('上市');assert.equal(a.state.projects.length,1);assert.equal(a.state.tasks.length,0);assert.equal(a.session().pid,p.id);assert.equal(p.planConfirmed,false)});
test('scope confirmation is idempotent and pins rule version',()=>{const {a,p}=setup();a.state.rules.version=99;assert.equal(p.ruleSnapshot.version,1);const n=a.state.tasks.length;assert.equal(a.confirmPlan(p.id,p.plan),false);assert.equal(a.state.tasks.length,n)});
test('draft tasks complete on saved output while approved tasks wait for review',()=>{const {a,p}=setup();a.saveArtifact('strategy',p.id);a.saveArtifact('mh',p.id);assert.equal(a.state.tasks.find(t=>t.type==='strategy').status,'complete');assert.equal(a.state.tasks.find(t=>t.type==='mh').status,'working')});
test('incidental research is an artifact without an extra business task',()=>{const {a,p}=setup();const n=a.state.tasks.length;a.saveArtifact('research',p.id);assert.equal(a.state.tasks.length,n);assert.equal(a.state.artifacts.length,1)});
test('a selected edit creates a candidate and does not alter prior or downstream content',()=>{const {a,p}=setup();const mh=a.saveArtifact('mh',p.id),pop=a.saveArtifact('pop',p.id);const old=a.current(mh),popOld=a.current(pop);a.state.aid=mh.id;const data=JSON.parse(JSON.stringify(old.data));data.claim='Nuevo mensaje';const v=a.editArtifact(mh.id,data);assert.notEqual(mh.candidate,mh.current);assert.notEqual(old.data.claim,'Nuevo mensaje');assert.equal(popOld.data.headline,old.data.claim);a.adopt(mh.id,v.id);assert.equal(a.current(mh).data.claim,'Nuevo mensaje');assert.equal(popOld.refs[0].rid,old.id)});
test('checks belong to a revision and are not inherited by edits',()=>{const {a,p}=setup();const ar=a.saveArtifact('pop',p.id);a.state.aid=ar.id;assert.equal(a.checkRevision(ar.id,ar.current).passed,true);const d=JSON.parse(JSON.stringify(a.current(ar).data));d.headline='100% 杀菌率';const v=a.editArtifact(ar.id,d);assert.equal(v.check,undefined);assert.equal(a.checkRevision(ar.id,v.id).passed,false);a.adopt(ar.id,v.id);assert.throws(()=>a.submit(ar.id,v.id),/检查/) });
test('reviewer must be independent, submissions immutable, decisions single-use',()=>{const {a,p}=setup();const ar=a.saveArtifact('mh',p.id);a.state.aid=ar.id;a.checkRevision(ar.id,ar.current);const s=a.submit(ar.id,ar.current);const snapshot=JSON.stringify(s.snapshot);assert.throws(()=>a.decide(s.id,'approved'),/审核人/);const d=JSON.parse(JSON.stringify(a.current(ar).data));d.claim='Later draft';a.editArtifact(ar.id,d);assert.equal(JSON.stringify(s.snapshot),snapshot);a.state.actor='reviewer';a.decide(s.id,'approved');assert.throws(()=>a.decide(s.id,'approved'),/已处理/);assert.equal(a.state.deliveries[0].status,'not_connected');assert.equal(a.state.tasks.find(t=>t.type==='mh').status,'working')});
test('return and resubmit keep old review and new fixed snapshot separate',()=>{const {a,p}=setup();const ar=a.saveArtifact('pop',p.id);a.state.aid=ar.id;a.checkRevision(ar.id,ar.current);const s=a.submit(ar.id,ar.current);a.state.actor='reviewer';assert.throws(()=>a.decide(s.id,'returned',''),/意见/);a.decide(s.id,'returned','缩短标题');a.state.actor='lin';const d=JSON.parse(JSON.stringify(a.current(ar).data));d.headline='SpaceMaster';const v=a.editArtifact(ar.id,d);a.adopt(ar.id,v.id);a.checkRevision(ar.id,v.id);const next=a.submit(ar.id,v.id);assert.notEqual(s.id,next.id);assert.notEqual(s.snapshot.data.headline,next.snapshot.data.headline);assert.equal(s.comments[0].text,'缩短标题')});
test('paused run survives reload and continues without duplicate completed artifacts',()=>{const {h,a,p}=setup();const r=a.beginRun(p.id,['research','strategy']);a.tickRun();a.tickRun();assert.equal(r.index,1);const re=harness(h.saved).api;assert.equal(re.state.runs[0].status,'paused');assert.equal(re.state.artifacts.length,1);re.state.runs[0].status='running';re.tickRun();re.tickRun();re.tickRun();assert.equal(re.state.artifacts.length,2);assert.equal(re.state.runs[0].status,'complete')});
test('disabled service stops at the missing capability and retains previous results',()=>{const {a,p}=setup();a.state.services.make=false;const r=a.beginRun(p.id,['assets','pop']);a.tickRun();a.tickRun();a.tickRun();assert.equal(r.status,'failed');assert.equal(a.state.artifacts.length,1);a.state.services.make=true;r.status='running';a.tickRun();a.tickRun();a.tickRun();assert.equal(a.state.artifacts.length,2)});
test('approval applies to current artifact only and cannot be repeated for the same revision',()=>{const {a,p}=setup();const ar=a.saveArtifact('pop',p.id);a.saveArtifact('mh',p.id);a.checkRevision(ar.id,ar.current);const s=a.submit(ar.id,ar.current);a.state.actor='reviewer';a.decide(s.id,'approved');assert.equal(a.state.tasks.find(t=>t.type==='pop').status,'complete');assert.equal(a.state.tasks.find(t=>t.type==='mh').status,'working');a.state.actor='lin';assert.throws(()=>a.submit(ar.id,ar.current),/已经批准/)});
test('unsupported capacity and wrong SKU cannot pass local fact checks',()=>{const {a,p}=setup();const ar=a.saveArtifact('pop',p.id);a.state.aid=ar.id;const d=JSON.parse(JSON.stringify(a.current(ar).data));d.benefit='Capacidad 800 L';const v=a.editArtifact(ar.id,d);assert.equal(a.checkRevision(ar.id,v.id).passed,false);d.benefit='570 L';d.footer='Another refrigerator';const v2=a.editArtifact(ar.id,d);assert.equal(a.checkRevision(ar.id,v2.id).passed,false)});
test('cancelled deliverable is not resurrected by a queued run',()=>{const {a,p}=setup();a.beginRun(p.id,['pop']);a.state.tasks.find(t=>t.type==='pop').status='cancelled';a.tickRun();a.tickRun();assert.equal(a.state.artifacts.length,0);assert.equal(a.state.tasks.find(t=>t.type==='pop').status,'cancelled')});
test('empty FABE selection yields a recoverable failure without a fabricated MH',()=>{const {a,p}=setup();const f=a.saveArtifact('fabe',p.id);a.current(f).data.points.forEach(p=>{p.selected=false});const r=a.beginRun(p.id,['mh']);a.tickRun();a.tickRun();assert.equal(r.status,'failed');assert.match(r.error,/有效价值/);assert.equal(a.state.artifacts.filter(x=>x.type==='mh').length,0)});
test('attachments from the originating conversation enter only its new project',()=>{const {api:a}=harness();a.session().files=[{name:'brief.md',text:'test brief'}];const p=a.createProject('上市');assert.equal(p.files[0].text,'test brief');p.files[0].text='project change';assert.equal(a.session().files[0].text,'test brief')});
