import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const run=(cmd,args,cwd=root)=>{const r=spawnSync(cmd,args,{cwd,encoding:'utf8',maxBuffer:20*1024*1024});if(r.status!==0)throw Error(r.stderr||r.stdout||String(r.error));return r.stdout;};
run(process.execPath,['src/marketing-desktop/build.mjs']);
const version=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version;
const out=path.join(root,'output/marketing-v62-prototype-'+version);fs.mkdirSync(out,{recursive:true});
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'mokina-package-'));
const name='Marketing Desktop V6.2 交互原型 '+version,stage=path.join(temp,name);fs.mkdirSync(stage);
for(const item of ['Marketing Desktop Demo.html','Lilith SpaceMaster Demo V6.html','README.md','package.json','src','public','vendor','tests','scripts','docs'])fs.cpSync(path.join(root,item),path.join(stage,item),{recursive:true,filter:src=>!['marketing-desktop.js','marketing-desktop.css','marketing-desktop.test.cjs'].includes(path.basename(src))});
fs.mkdirSync(path.join(stage,'output'),{recursive:true});
if(fs.existsSync(path.join(root,'output/playwright')))fs.cpSync(path.join(root,'output/playwright'),path.join(stage,'output/playwright'),{recursive:true});
const tap=run('npm',['test'],stage);fs.writeFileSync(path.join(out,'tests.tap'),tap);fs.writeFileSync(path.join(stage,'output/tests.tap'),tap);
run('npm',['run','build'],stage);
const digest=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
if(digest(path.join(root,'Marketing Desktop Demo.html'))!==digest(path.join(stage,'Marketing Desktop Demo.html')))throw Error('Staged rebuild differs');
const sums=[];function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())walk(p);else sums.push(digest(p)+'  '+path.relative(stage,p));}}walk(stage);fs.writeFileSync(path.join(stage,'SHA256SUMS'),sums.join('\n')+'\n');
const stagedZip=path.join(temp,name+'.zip');run('zip',['-qr',stagedZip,name],temp);
const unpack=path.join(temp,'unpacked');fs.mkdirSync(unpack);run('unzip',['-q',stagedZip,'-d',unpack]);
const unpackRoot=path.join(unpack,name);run('npm',['run','build'],unpackRoot);const unpackTests=run('npm',['test'],unpackRoot);
if(digest(path.join(unpackRoot,'Marketing Desktop Demo.html'))!==digest(path.join(root,'Marketing Desktop Demo.html')))throw Error('Unpacked rebuild differs');
run('npm',['run','verify:downloads'],unpackRoot);
run('npm',['run','verify:repair-downloads'],unpackRoot);
const zipPath=path.join(out,name+'.zip');fs.copyFileSync(stagedZip,zipPath);
fs.writeFileSync(path.join(out,'unpacked-tests.tap'),unpackTests);
fs.writeFileSync(path.join(out,'package-check.json'),JSON.stringify({created:new Date().toISOString(),zip:zipPath,sha256:digest(zipPath),unzip:true,rebuild:true,tests:true,downloadContentChecks:true,files:sums.length,htmlSha256:digest(path.join(root,'Marketing Desktop Demo.html')),baselineSha256:digest(path.join(root,'Lilith SpaceMaster Demo V6.html'))},null,2));
// Only this script's mkdtemp tree is removed; project files and user backups are untouched.
fs.rmSync(temp,{recursive:true});console.log(zipPath);
